// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/resources/jflex/Lexer.flex

package com.olc1.golite.lexer;


@SuppressWarnings("fallthrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\2\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\4\21\1\22\1\21"+
    "\1\23\3\21\1\24\1\25\1\26\1\27\1\30\2\0"+
    "\1\31\4\32\1\33\2\32\1\34\5\32\1\35\1\36"+
    "\3\32\1\37\6\32\1\40\1\41\1\42\1\0\1\43"+
    "\1\0\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\32\1\55\1\56\1\57\1\60\1\61"+
    "\1\62\1\32\1\63\1\64\1\65\1\66\1\67\1\70"+
    "\1\71\1\72\1\32\1\73\1\74\1\75\7\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\5\23\1\24\1\25"+
    "\15\23\1\26\1\1\1\27\1\30\1\0\1\31\1\0"+
    "\1\32\2\0\1\33\1\34\1\35\1\36\1\0\1\2"+
    "\1\0\1\37\1\40\1\41\21\23\1\42\12\23\1\43"+
    "\1\44\1\0\1\45\16\23\1\46\1\47\1\23\1\50"+
    "\1\51\1\52\7\23\1\53\1\2\1\54\5\23\1\55"+
    "\1\23\1\56\2\23\1\57\2\23\1\60\2\23\1\61"+
    "\4\23\1\62\1\63\4\23\1\64\2\23\1\65\11\23"+
    "\1\66\1\67\4\23\1\70\1\71\1\23\1\72\1\73"+
    "\1\23\1\74\1\23\1\75\1\76\1\77\1\100\1\23"+
    "\1\101\1\23\1\102";

  private static int [] zzUnpackAction() {
    int [] result = new int[186];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\370\0\76\0\u0136\0\u0174"+
    "\0\76\0\76\0\76\0\u01b2\0\76\0\u01f0\0\76\0\u022e"+
    "\0\u026c\0\76\0\76\0\u02aa\0\u02e8\0\u0326\0\u0364\0\u03a2"+
    "\0\u03e0\0\u041e\0\u045c\0\76\0\76\0\u049a\0\u04d8\0\u0516"+
    "\0\u0554\0\u0592\0\u05d0\0\u060e\0\u064c\0\u068a\0\u06c8\0\u0706"+
    "\0\u0744\0\u0782\0\76\0\u07c0\0\76\0\76\0\370\0\76"+
    "\0\u07fe\0\76\0\u083c\0\u087a\0\76\0\76\0\76\0\76"+
    "\0\u08b8\0\u08f6\0\u0934\0\76\0\76\0\76\0\u0972\0\u09b0"+
    "\0\u09ee\0\u0a2c\0\u0a6a\0\u0aa8\0\u0ae6\0\u0b24\0\u0b62\0\u0ba0"+
    "\0\u0bde\0\u0c1c\0\u0c5a\0\u0c98\0\u0cd6\0\u0d14\0\u0d52\0\u03a2"+
    "\0\u0d90\0\u0dce\0\u0e0c\0\u0e4a\0\u0e88\0\u0ec6\0\u0f04\0\u0f42"+
    "\0\u0f80\0\u0fbe\0\76\0\76\0\u0ffc\0\u0934\0\u103a\0\u1078"+
    "\0\u10b6\0\u10f4\0\u1132\0\u1170\0\u11ae\0\u11ec\0\u122a\0\u1268"+
    "\0\u12a6\0\u12e4\0\u1322\0\u1360\0\u03a2\0\u03a2\0\u139e\0\u03a2"+
    "\0\u03a2\0\u03a2\0\u13dc\0\u141a\0\u1458\0\u1496\0\u14d4\0\u1512"+
    "\0\u1550\0\u03a2\0\76\0\u03a2\0\u158e\0\u15cc\0\u160a\0\u1648"+
    "\0\u1686\0\u03a2\0\u16c4\0\u03a2\0\u1702\0\u1740\0\u03a2\0\u177e"+
    "\0\u17bc\0\u03a2\0\u17fa\0\u1838\0\u03a2\0\u1876\0\u18b4\0\u18f2"+
    "\0\u1930\0\u03a2\0\u03a2\0\u196e\0\u19ac\0\u19ea\0\u1a28\0\u03a2"+
    "\0\u1a66\0\u1aa4\0\u03a2\0\u1ae2\0\u1b20\0\u1b5e\0\u1b9c\0\u1bda"+
    "\0\u1c18\0\u1c56\0\u1c94\0\u1cd2\0\u03a2\0\u03a2\0\u1d10\0\u1d4e"+
    "\0\u1d8c\0\u1dca\0\u03a2\0\u03a2\0\u1e08\0\u03a2\0\u03a2\0\u1e46"+
    "\0\u03a2\0\u1e84\0\u03a2\0\u03a2\0\u03a2\0\u03a2\0\u1ec2\0\u03a2"+
    "\0\u1f00\0\u03a2";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[186];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\3\21\1\22\1\23\1\24\1\25\1\26\1\27\2\30"+
    "\1\31\1\30\1\32\1\33\1\34\1\2\1\35\1\2"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\2\30\1\44"+
    "\1\30\1\45\1\30\1\46\2\30\1\47\1\50\1\51"+
    "\1\30\1\52\3\30\1\53\1\54\1\55\77\0\2\3"+
    "\122\0\1\56\46\0\5\57\1\60\33\57\1\61\34\57"+
    "\7\0\1\62\66\0\10\63\1\0\30\63\1\64\34\63"+
    "\14\0\1\65\12\0\1\66\64\0\1\67\10\0\1\70"+
    "\61\0\1\71\4\0\1\72\74\0\1\73\1\0\3\21"+
    "\101\0\1\74\75\0\1\75\75\0\1\76\67\0\3\30"+
    "\5\0\7\30\3\0\22\30\1\77\5\30\24\0\3\30"+
    "\5\0\7\30\3\0\30\30\24\0\3\30\5\0\7\30"+
    "\3\0\15\30\1\100\12\30\24\0\3\30\5\0\7\30"+
    "\3\0\1\30\1\101\16\30\1\102\7\30\24\0\3\30"+
    "\5\0\7\30\3\0\27\30\1\103\24\0\3\30\5\0"+
    "\7\30\3\0\17\30\1\104\10\30\24\0\3\30\5\0"+
    "\7\30\3\0\16\30\1\105\1\30\1\106\7\30\24\0"+
    "\3\30\5\0\7\30\3\0\1\30\1\107\14\30\1\110"+
    "\11\30\24\0\3\30\5\0\7\30\3\0\5\30\1\111"+
    "\22\30\24\0\3\30\5\0\7\30\3\0\13\30\1\112"+
    "\14\30\24\0\3\30\5\0\7\30\3\0\1\30\1\113"+
    "\11\30\1\114\1\115\1\30\1\116\4\30\1\117\4\30"+
    "\24\0\3\30\5\0\7\30\3\0\6\30\1\120\6\30"+
    "\1\121\12\30\24\0\3\30\5\0\7\30\3\0\5\30"+
    "\1\122\22\30\24\0\3\30\5\0\7\30\3\0\11\30"+
    "\1\123\16\30\24\0\3\30\5\0\7\30\3\0\5\30"+
    "\1\124\15\30\1\125\4\30\24\0\3\30\5\0\7\30"+
    "\3\0\13\30\1\126\6\30\1\127\2\30\1\130\2\30"+
    "\24\0\3\30\5\0\7\30\3\0\20\30\1\131\7\30"+
    "\24\0\3\30\5\0\7\30\3\0\1\30\1\132\26\30"+
    "\77\0\1\133\1\0\2\57\2\0\72\57\10\0\1\134"+
    "\65\0\2\63\2\0\72\63\13\71\1\135\62\71\2\72"+
    "\2\0\72\72\21\0\3\136\73\0\3\30\5\0\7\30"+
    "\3\0\16\30\1\137\11\30\24\0\3\30\5\0\7\30"+
    "\3\0\4\30\1\140\23\30\24\0\3\30\5\0\7\30"+
    "\3\0\20\30\1\141\7\30\24\0\3\30\5\0\7\30"+
    "\3\0\11\30\1\142\16\30\24\0\3\30\5\0\7\30"+
    "\3\0\17\30\1\143\10\30\24\0\3\30\5\0\7\30"+
    "\3\0\17\30\1\144\10\30\24\0\3\30\5\0\7\30"+
    "\3\0\16\30\1\145\11\30\24\0\3\30\5\0\7\30"+
    "\3\0\5\30\1\146\22\30\24\0\3\30\5\0\7\30"+
    "\3\0\21\30\1\147\6\30\24\0\3\30\5\0\7\30"+
    "\3\0\15\30\1\150\12\30\24\0\3\30\5\0\7\30"+
    "\3\0\6\30\1\151\21\30\24\0\3\30\5\0\7\30"+
    "\3\0\21\30\1\152\6\30\24\0\3\30\5\0\7\30"+
    "\3\0\13\30\1\153\14\30\24\0\3\30\5\0\7\30"+
    "\3\0\16\30\1\154\11\30\24\0\3\30\5\0\7\30"+
    "\3\0\22\30\1\155\5\30\24\0\3\30\5\0\7\30"+
    "\3\0\20\30\1\156\7\30\24\0\3\30\5\0\7\30"+
    "\3\0\15\30\1\157\12\30\24\0\3\30\5\0\7\30"+
    "\3\0\22\30\1\160\5\30\24\0\3\30\5\0\7\30"+
    "\3\0\15\30\1\161\12\30\24\0\3\30\5\0\7\30"+
    "\3\0\13\30\1\162\14\30\24\0\3\30\5\0\7\30"+
    "\3\0\6\30\1\163\13\30\1\164\5\30\24\0\3\30"+
    "\5\0\7\30\3\0\15\30\1\165\12\30\24\0\3\30"+
    "\5\0\7\30\3\0\11\30\1\166\16\30\24\0\3\30"+
    "\5\0\7\30\3\0\20\30\1\167\7\30\24\0\3\30"+
    "\5\0\7\30\3\0\11\30\1\170\16\30\24\0\3\30"+
    "\5\0\7\30\3\0\23\30\1\171\4\30\24\0\3\30"+
    "\5\0\7\30\3\0\20\30\1\172\7\30\3\0\13\71"+
    "\1\135\4\71\1\173\55\71\21\0\3\30\5\0\7\30"+
    "\3\0\11\30\1\174\16\30\24\0\3\30\5\0\7\30"+
    "\3\0\5\30\1\175\22\30\24\0\3\30\5\0\7\30"+
    "\3\0\21\30\1\176\6\30\24\0\3\30\5\0\7\30"+
    "\3\0\15\30\1\177\12\30\24\0\3\30\5\0\7\30"+
    "\3\0\5\30\1\200\22\30\24\0\3\30\5\0\7\30"+
    "\3\0\5\30\1\201\22\30\24\0\3\30\5\0\7\30"+
    "\3\0\13\30\1\202\14\30\24\0\3\30\5\0\7\30"+
    "\3\0\1\30\1\203\26\30\24\0\3\30\5\0\7\30"+
    "\3\0\5\30\1\204\22\30\24\0\3\30\5\0\7\30"+
    "\3\0\22\30\1\205\5\30\24\0\3\30\5\0\7\30"+
    "\3\0\1\30\1\206\26\30\24\0\3\30\5\0\7\30"+
    "\3\0\5\30\1\207\22\30\24\0\3\30\5\0\7\30"+
    "\3\0\21\30\1\210\6\30\24\0\3\30\5\0\7\30"+
    "\3\0\1\30\1\211\26\30\24\0\3\30\5\0\7\30"+
    "\3\0\3\30\1\212\24\30\24\0\3\30\5\0\7\30"+
    "\3\0\13\30\1\213\14\30\24\0\3\30\5\0\7\30"+
    "\3\0\23\30\1\214\4\30\24\0\3\30\5\0\7\30"+
    "\3\0\5\30\1\215\22\30\24\0\3\30\5\0\7\30"+
    "\3\0\3\30\1\216\24\30\24\0\3\30\5\0\7\30"+
    "\3\0\3\30\1\217\5\30\1\220\16\30\24\0\3\30"+
    "\5\0\7\30\3\0\22\30\1\221\5\30\24\0\3\30"+
    "\5\0\7\30\3\0\5\30\1\222\22\30\24\0\3\30"+
    "\5\0\7\30\3\0\26\30\1\223\1\30\24\0\3\30"+
    "\5\0\7\30\3\0\5\30\1\224\22\30\24\0\3\30"+
    "\5\0\7\30\3\0\22\30\1\225\5\30\24\0\3\30"+
    "\5\0\4\30\1\226\2\30\3\0\30\30\24\0\3\30"+
    "\5\0\7\30\3\0\15\30\1\227\12\30\24\0\3\30"+
    "\5\0\7\30\3\0\12\30\1\230\15\30\24\0\3\30"+
    "\5\0\7\30\3\0\11\30\1\231\16\30\24\0\3\30"+
    "\5\0\7\30\3\0\23\30\1\232\4\30\24\0\3\30"+
    "\5\0\7\30\3\0\5\30\1\233\22\30\24\0\3\30"+
    "\5\0\7\30\3\0\22\30\1\234\5\30\24\0\3\30"+
    "\5\0\7\30\3\0\5\30\1\235\22\30\24\0\3\30"+
    "\5\0\7\30\3\0\20\30\1\236\7\30\24\0\3\30"+
    "\5\0\7\30\3\0\5\30\1\237\22\30\24\0\3\30"+
    "\5\0\7\30\3\0\16\30\1\240\11\30\24\0\3\30"+
    "\5\0\7\30\3\0\15\30\1\241\12\30\24\0\3\30"+
    "\5\0\7\30\3\0\3\30\1\242\24\30\24\0\3\30"+
    "\5\0\2\30\1\243\4\30\3\0\30\30\24\0\3\30"+
    "\5\0\7\30\3\0\13\30\1\244\14\30\24\0\3\30"+
    "\5\0\7\30\3\0\6\30\1\245\21\30\24\0\3\30"+
    "\5\0\7\30\3\0\4\30\1\246\23\30\24\0\3\30"+
    "\5\0\7\30\3\0\15\30\1\247\12\30\24\0\3\30"+
    "\5\0\7\30\3\0\13\30\1\250\14\30\24\0\2\30"+
    "\1\251\5\0\7\30\3\0\30\30\24\0\3\30\5\0"+
    "\7\30\3\0\3\30\1\252\24\30\24\0\3\30\5\0"+
    "\7\30\3\0\15\30\1\253\12\30\24\0\3\30\5\0"+
    "\7\30\3\0\21\30\1\254\6\30\24\0\3\30\5\0"+
    "\7\30\3\0\15\30\1\255\12\30\24\0\3\30\5\0"+
    "\7\30\3\0\7\30\1\256\20\30\24\0\3\30\5\0"+
    "\7\30\3\0\10\30\1\257\17\30\24\0\3\30\5\0"+
    "\7\30\3\0\13\30\1\260\14\30\24\0\3\30\5\0"+
    "\7\30\3\0\15\30\1\261\12\30\24\0\3\30\5\0"+
    "\7\30\3\0\23\30\1\262\4\30\24\0\3\30\5\0"+
    "\7\30\3\0\22\30\1\263\5\30\24\0\1\30\1\264"+
    "\1\30\5\0\7\30\3\0\30\30\24\0\3\30\5\0"+
    "\7\30\3\0\22\30\1\265\5\30\24\0\3\30\5\0"+
    "\7\30\3\0\24\30\1\266\3\30\24\0\3\30\5\0"+
    "\7\30\3\0\16\30\1\267\11\30\24\0\3\30\5\0"+
    "\7\30\3\0\5\30\1\270\22\30\24\0\3\30\5\0"+
    "\7\30\3\0\1\30\1\271\26\30\24\0\3\30\5\0"+
    "\7\30\3\0\22\30\1\272\5\30\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[7998];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\3\11\1\1\1\11"+
    "\1\1\1\11\2\1\2\11\10\1\2\11\15\1\1\11"+
    "\1\1\2\11\1\0\1\11\1\0\1\11\2\0\4\11"+
    "\1\0\1\1\1\0\3\11\34\1\2\11\1\0\35\1"+
    "\1\11\77\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[186];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token (TipoToken tipo, String lexema){
        return new Token(tipo, lexema, yyline + 1, yycolumn + 1);
    }    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return token(TipoToken.EOF, "EOF");
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(TipoToken.ERROR, yytext());
            }
          // fall through
          case 67: break;
          case 2:
            { 
            }
          // fall through
          case 68: break;
          case 3:
            { return token(TipoToken.NOT, yytext());
            }
          // fall through
          case 69: break;
          case 4:
            { return token(TipoToken.MODULO, yytext());
            }
          // fall through
          case 70: break;
          case 5:
            { return token(TipoToken.PARENTESIS_IZQ, yytext());
            }
          // fall through
          case 71: break;
          case 6:
            { return token(TipoToken.PARENTESIS_DER, yytext());
            }
          // fall through
          case 72: break;
          case 7:
            { return token(TipoToken.MULTIPLICACION, yytext());
            }
          // fall through
          case 73: break;
          case 8:
            { return token(TipoToken.MAS, yytext());
            }
          // fall through
          case 74: break;
          case 9:
            { return token(TipoToken.COMA, yytext());
            }
          // fall through
          case 75: break;
          case 10:
            { return token(TipoToken.MENOS, yytext());
            }
          // fall through
          case 76: break;
          case 11:
            { return token(TipoToken.PUNTO, yytext());
            }
          // fall through
          case 77: break;
          case 12:
            { return token(TipoToken.DIVISION, yytext());
            }
          // fall through
          case 78: break;
          case 13:
            { return token(TipoToken.ENTERO, yytext());
            }
          // fall through
          case 79: break;
          case 14:
            { return token(TipoToken.DOS_PUNTOS, yytext());
            }
          // fall through
          case 80: break;
          case 15:
            { return token(TipoToken.PUNTO_COMA, yytext());
            }
          // fall through
          case 81: break;
          case 16:
            { return token(TipoToken.MENOR, yytext());
            }
          // fall through
          case 82: break;
          case 17:
            { return token(TipoToken.IGUAL, yytext());
            }
          // fall through
          case 83: break;
          case 18:
            { return token(TipoToken.MAYOR, yytext());
            }
          // fall through
          case 84: break;
          case 19:
            { return token(TipoToken.IDENTIFICADOR, yytext());
            }
          // fall through
          case 85: break;
          case 20:
            { return token(TipoToken.CORCHETE_IZQ, yytext());
            }
          // fall through
          case 86: break;
          case 21:
            { return token(TipoToken.CORCHETE_DER, yytext());
            }
          // fall through
          case 87: break;
          case 22:
            { return token(TipoToken.LLAVE_IZQ, yytext());
            }
          // fall through
          case 88: break;
          case 23:
            { return token(TipoToken.LLAVE_DER, yytext());
            }
          // fall through
          case 89: break;
          case 24:
            { return token(TipoToken.DIFERENTE, yytext());
            }
          // fall through
          case 90: break;
          case 25:
            { return token(TipoToken.CADENA, yytext());
            }
          // fall through
          case 91: break;
          case 26:
            { return token(TipoToken.AND, yytext());
            }
          // fall through
          case 92: break;
          case 27:
            { return token(TipoToken.INCREMENTO, yytext());
            }
          // fall through
          case 93: break;
          case 28:
            { return token(TipoToken.MAS_IGUAL, yytext());
            }
          // fall through
          case 94: break;
          case 29:
            { return token(TipoToken.DECREMENTO, yytext());
            }
          // fall through
          case 95: break;
          case 30:
            { return token(TipoToken.MENOS_IGUAL, yytext());
            }
          // fall through
          case 96: break;
          case 31:
            { return token(TipoToken.MENOR_IGUAL, yytext());
            }
          // fall through
          case 97: break;
          case 32:
            { return token(TipoToken.IGUAL_IGUAL, yytext());
            }
          // fall through
          case 98: break;
          case 33:
            { return token(TipoToken.MAYOR_IGUAL, yytext());
            }
          // fall through
          case 99: break;
          case 34:
            { return token(TipoToken.IF, yytext());
            }
          // fall through
          case 100: break;
          case 35:
            { return token(TipoToken.OR, yytext());
            }
          // fall through
          case 101: break;
          case 36:
            { return token(TipoToken.LITERAL_RUNE, yytext());
            }
          // fall through
          case 102: break;
          case 37:
            { return token(TipoToken.DECIMAL, yytext());
            }
          // fall through
          case 103: break;
          case 38:
            { return token(TipoToken.FMT, yytext());
            }
          // fall through
          case 104: break;
          case 39:
            { return token(TipoToken.FOR, yytext());
            }
          // fall through
          case 105: break;
          case 40:
            { return token(TipoToken.INT, yytext());
            }
          // fall through
          case 106: break;
          case 41:
            { return token(TipoToken.LEN, yytext());
            }
          // fall through
          case 107: break;
          case 42:
            { return token(TipoToken.NIL, yytext());
            }
          // fall through
          case 108: break;
          case 43:
            { return token(TipoToken.VAR, yytext());
            }
          // fall through
          case 109: break;
          case 44:
            { return token(TipoToken.ATOI, yytext());
            }
          // fall through
          case 110: break;
          case 45:
            { return token(TipoToken.BOOL, yytext());
            }
          // fall through
          case 111: break;
          case 46:
            { return token(TipoToken.CASE, yytext());
            }
          // fall through
          case 112: break;
          case 47:
            { return token(TipoToken.ELSE, yytext());
            }
          // fall through
          case 113: break;
          case 48:
            { return token(TipoToken.FUNC, yytext());
            }
          // fall through
          case 114: break;
          case 49:
            { return token(TipoToken.RUNE, yytext());
            }
          // fall through
          case 115: break;
          case 50:
            { return token(TipoToken.TRUE, yytext());
            }
          // fall through
          case 116: break;
          case 51:
            { return token(TipoToken.INDEX, yytext());
            }
          // fall through
          case 117: break;
          case 52:
            { return token(TipoToken.BREAK, yytext());
            }
          // fall through
          case 118: break;
          case 53:
            { return token(TipoToken.FALSE, yytext());
            }
          // fall through
          case 119: break;
          case 54:
            { return token(TipoToken.TYPEOF, yytext());
            }
          // fall through
          case 120: break;
          case 55:
            { return token( TipoToken.APPEND, yytext());
            }
          // fall through
          case 121: break;
          case 56:
            { return token(TipoToken.RETURN, yytext());
            }
          // fall through
          case 122: break;
          case 57:
            { return token(TipoToken.SLICES, yytext());
            }
          // fall through
          case 123: break;
          case 58:
            { return token(TipoToken.STRING, yytext());
            }
          // fall through
          case 124: break;
          case 59:
            { return token(TipoToken.SWITCH, yytext());
            }
          // fall through
          case 125: break;
          case 60:
            { return token(TipoToken.PRINTLN, yytext());
            }
          // fall through
          case 126: break;
          case 61:
            { return token(TipoToken.DEFAULT, yytext());
            }
          // fall through
          case 127: break;
          case 62:
            { return token(TipoToken.FLOAT64, yytext());
            }
          // fall through
          case 128: break;
          case 63:
            { return token(TipoToken.REFLECT, yytext());
            }
          // fall through
          case 129: break;
          case 64:
            { return token(TipoToken.STRCONV, yytext());
            }
          // fall through
          case 130: break;
          case 65:
            { return token(TipoToken.CONTINUE, yytext());
            }
          // fall through
          case 131: break;
          case 66:
            { return token(TipoToken.PARSEFLOAT, yytext());
            }
          // fall through
          case 132: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
