// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/resources/jflex/Lexer.flex

package com.olc1.golite.lexer;


@SuppressWarnings("fallthrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\2\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\4\21\1\22\1\21"+
    "\1\23\3\21\1\24\1\25\1\26\1\27\1\30\2\0"+
    "\1\31\4\32\1\33\10\32\1\34\1\35\3\32\1\36"+
    "\6\32\1\0\1\37\2\0\1\40\1\0\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\32"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\1\32\1\60"+
    "\1\61\1\62\1\63\1\64\1\65\1\32\1\66\1\32"+
    "\1\67\1\70\1\71\7\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\17\23\1\24\1\1"+
    "\1\25\1\26\1\0\1\27\1\0\1\30\2\0\1\31"+
    "\1\32\1\33\1\34\1\0\1\2\1\0\1\35\1\36"+
    "\1\37\17\23\1\40\10\23\1\41\1\42\1\0\1\43"+
    "\14\23\1\44\1\45\1\23\1\46\1\47\6\23\1\50"+
    "\1\2\1\51\3\23\1\52\1\23\1\53\2\23\1\54"+
    "\2\23\1\55\2\23\1\56\3\23\1\57\3\23\1\60"+
    "\2\23\1\61\10\23\1\62\4\23\1\63\1\23\1\64"+
    "\1\65\1\23\1\66\1\23\1\67\1\70\1\71\1\72"+
    "\1\23\1\73\1\23\1\74";

  private static int [] zzUnpackAction() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\350\0\72\0\u0122\0\u015c"+
    "\0\72\0\72\0\72\0\u0196\0\72\0\u01d0\0\72\0\u020a"+
    "\0\u0244\0\72\0\72\0\u027e\0\u02b8\0\u02f2\0\u032c\0\u0366"+
    "\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2\0\u04fc\0\u0536"+
    "\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658\0\72\0\u0692\0\72"+
    "\0\72\0\350\0\72\0\u06cc\0\72\0\u0706\0\u0740\0\72"+
    "\0\72\0\72\0\72\0\u077a\0\u07b4\0\u07ee\0\72\0\72"+
    "\0\72\0\u0828\0\u0862\0\u089c\0\u08d6\0\u0910\0\u094a\0\u0984"+
    "\0\u09be\0\u09f8\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a\0\u0b54"+
    "\0\u0366\0\u0b8e\0\u0bc8\0\u0c02\0\u0c3c\0\u0c76\0\u0cb0\0\u0cea"+
    "\0\u0d24\0\72\0\72\0\u0d5e\0\u07ee\0\u0d98\0\u0dd2\0\u0e0c"+
    "\0\u0e46\0\u0e80\0\u0eba\0\u0ef4\0\u0f2e\0\u0f68\0\u0fa2\0\u0fdc"+
    "\0\u1016\0\u0366\0\u0366\0\u1050\0\u0366\0\u0366\0\u108a\0\u10c4"+
    "\0\u10fe\0\u1138\0\u1172\0\u11ac\0\u0366\0\72\0\u0366\0\u11e6"+
    "\0\u1220\0\u125a\0\u0366\0\u1294\0\u0366\0\u12ce\0\u1308\0\u0366"+
    "\0\u1342\0\u137c\0\u0366\0\u13b6\0\u13f0\0\u0366\0\u142a\0\u1464"+
    "\0\u149e\0\u0366\0\u14d8\0\u1512\0\u154c\0\u0366\0\u1586\0\u15c0"+
    "\0\u0366\0\u15fa\0\u1634\0\u166e\0\u16a8\0\u16e2\0\u171c\0\u1756"+
    "\0\u1790\0\u0366\0\u17ca\0\u1804\0\u183e\0\u1878\0\u0366\0\u18b2"+
    "\0\u0366\0\u0366\0\u18ec\0\u0366\0\u1926\0\u0366\0\u0366\0\u0366"+
    "\0\u0366\0\u1960\0\u0366\0\u199a\0\u0366";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\3\21\1\22\1\23\1\24\1\25\1\26\1\27\3\30"+
    "\1\31\1\32\2\2\1\30\1\33\1\34\1\35\1\36"+
    "\1\37\2\30\1\40\3\30\1\41\2\30\1\42\1\43"+
    "\1\44\1\30\1\45\2\30\1\46\1\47\1\50\73\0"+
    "\2\3\116\0\1\51\42\0\5\52\1\53\31\52\1\54"+
    "\32\52\7\0\1\55\62\0\10\56\1\0\26\56\1\57"+
    "\32\56\14\0\1\60\12\0\1\61\60\0\1\62\10\0"+
    "\1\63\55\0\1\64\4\0\1\65\70\0\1\66\1\0"+
    "\3\21\75\0\1\67\71\0\1\70\71\0\1\71\63\0"+
    "\3\30\5\0\6\30\1\0\22\30\1\72\4\30\24\0"+
    "\3\30\5\0\6\30\1\0\27\30\24\0\3\30\5\0"+
    "\6\30\1\0\1\30\1\73\16\30\1\74\6\30\24\0"+
    "\3\30\5\0\6\30\1\0\26\30\1\75\24\0\3\30"+
    "\5\0\6\30\1\0\16\30\1\76\1\30\1\77\6\30"+
    "\24\0\3\30\5\0\6\30\1\0\1\30\1\100\14\30"+
    "\1\101\10\30\24\0\3\30\5\0\6\30\1\0\5\30"+
    "\1\102\21\30\24\0\3\30\5\0\6\30\1\0\13\30"+
    "\1\103\13\30\24\0\3\30\5\0\6\30\1\0\1\30"+
    "\1\104\11\30\1\105\1\106\1\30\1\107\4\30\1\110"+
    "\3\30\24\0\3\30\5\0\6\30\1\0\6\30\1\111"+
    "\6\30\1\112\11\30\24\0\3\30\5\0\6\30\1\0"+
    "\11\30\1\113\15\30\24\0\3\30\5\0\6\30\1\0"+
    "\5\30\1\114\15\30\1\115\3\30\24\0\3\30\5\0"+
    "\6\30\1\0\22\30\1\116\2\30\1\117\1\30\24\0"+
    "\3\30\5\0\6\30\1\0\20\30\1\120\6\30\24\0"+
    "\3\30\5\0\6\30\1\0\1\30\1\121\25\30\73\0"+
    "\1\122\1\0\2\52\2\0\66\52\10\0\1\123\61\0"+
    "\2\56\2\0\66\56\13\64\1\124\56\64\2\65\2\0"+
    "\66\65\21\0\3\125\67\0\3\30\5\0\6\30\1\0"+
    "\16\30\1\126\10\30\24\0\3\30\5\0\6\30\1\0"+
    "\20\30\1\127\6\30\24\0\3\30\5\0\6\30\1\0"+
    "\11\30\1\130\15\30\24\0\3\30\5\0\6\30\1\0"+
    "\17\30\1\131\7\30\24\0\3\30\5\0\6\30\1\0"+
    "\16\30\1\132\10\30\24\0\3\30\5\0\6\30\1\0"+
    "\5\30\1\133\21\30\24\0\3\30\5\0\6\30\1\0"+
    "\21\30\1\134\5\30\24\0\3\30\5\0\6\30\1\0"+
    "\15\30\1\135\11\30\24\0\3\30\5\0\6\30\1\0"+
    "\6\30\1\136\20\30\24\0\3\30\5\0\6\30\1\0"+
    "\21\30\1\137\5\30\24\0\3\30\5\0\6\30\1\0"+
    "\13\30\1\140\13\30\24\0\3\30\5\0\6\30\1\0"+
    "\16\30\1\141\10\30\24\0\3\30\5\0\6\30\1\0"+
    "\22\30\1\142\4\30\24\0\3\30\5\0\6\30\1\0"+
    "\20\30\1\143\6\30\24\0\3\30\5\0\6\30\1\0"+
    "\15\30\1\144\11\30\24\0\3\30\5\0\6\30\1\0"+
    "\22\30\1\145\4\30\24\0\3\30\5\0\6\30\1\0"+
    "\13\30\1\146\13\30\24\0\3\30\5\0\6\30\1\0"+
    "\6\30\1\147\13\30\1\150\4\30\24\0\3\30\5\0"+
    "\6\30\1\0\15\30\1\151\11\30\24\0\3\30\5\0"+
    "\6\30\1\0\20\30\1\152\6\30\24\0\3\30\5\0"+
    "\6\30\1\0\11\30\1\153\15\30\24\0\3\30\5\0"+
    "\6\30\1\0\23\30\1\154\3\30\24\0\3\30\5\0"+
    "\6\30\1\0\20\30\1\155\6\30\3\0\13\64\1\124"+
    "\4\64\1\156\51\64\21\0\3\30\5\0\6\30\1\0"+
    "\11\30\1\157\15\30\24\0\3\30\5\0\6\30\1\0"+
    "\21\30\1\160\5\30\24\0\3\30\5\0\6\30\1\0"+
    "\15\30\1\161\11\30\24\0\3\30\5\0\6\30\1\0"+
    "\5\30\1\162\21\30\24\0\3\30\5\0\6\30\1\0"+
    "\13\30\1\163\13\30\24\0\3\30\5\0\6\30\1\0"+
    "\1\30\1\164\25\30\24\0\3\30\5\0\6\30\1\0"+
    "\5\30\1\165\21\30\24\0\3\30\5\0\6\30\1\0"+
    "\22\30\1\166\4\30\24\0\3\30\5\0\6\30\1\0"+
    "\1\30\1\167\25\30\24\0\3\30\5\0\6\30\1\0"+
    "\5\30\1\170\21\30\24\0\3\30\5\0\6\30\1\0"+
    "\21\30\1\171\5\30\24\0\3\30\5\0\6\30\1\0"+
    "\1\30\1\172\25\30\24\0\3\30\5\0\6\30\1\0"+
    "\3\30\1\173\23\30\24\0\3\30\5\0\6\30\1\0"+
    "\13\30\1\174\13\30\24\0\3\30\5\0\6\30\1\0"+
    "\23\30\1\175\3\30\24\0\3\30\5\0\6\30\1\0"+
    "\5\30\1\176\21\30\24\0\3\30\5\0\6\30\1\0"+
    "\3\30\1\177\5\30\1\200\15\30\24\0\3\30\5\0"+
    "\6\30\1\0\22\30\1\201\4\30\24\0\3\30\5\0"+
    "\6\30\1\0\5\30\1\202\21\30\24\0\3\30\5\0"+
    "\6\30\1\0\5\30\1\203\21\30\24\0\3\30\5\0"+
    "\6\30\1\0\22\30\1\204\4\30\24\0\3\30\5\0"+
    "\3\30\1\205\2\30\1\0\27\30\24\0\3\30\5\0"+
    "\6\30\1\0\12\30\1\206\14\30\24\0\3\30\5\0"+
    "\6\30\1\0\11\30\1\207\15\30\24\0\3\30\5\0"+
    "\6\30\1\0\23\30\1\210\3\30\24\0\3\30\5\0"+
    "\6\30\1\0\5\30\1\211\21\30\24\0\3\30\5\0"+
    "\6\30\1\0\22\30\1\212\4\30\24\0\3\30\5\0"+
    "\6\30\1\0\5\30\1\213\21\30\24\0\3\30\5\0"+
    "\6\30\1\0\20\30\1\214\6\30\24\0\3\30\5\0"+
    "\6\30\1\0\16\30\1\215\10\30\24\0\3\30\5\0"+
    "\6\30\1\0\15\30\1\216\11\30\24\0\3\30\5\0"+
    "\6\30\1\0\3\30\1\217\23\30\24\0\3\30\5\0"+
    "\2\30\1\220\3\30\1\0\27\30\24\0\3\30\5\0"+
    "\6\30\1\0\13\30\1\221\13\30\24\0\3\30\5\0"+
    "\6\30\1\0\6\30\1\222\20\30\24\0\3\30\5\0"+
    "\6\30\1\0\15\30\1\223\11\30\24\0\3\30\5\0"+
    "\6\30\1\0\13\30\1\224\13\30\24\0\2\30\1\225"+
    "\5\0\6\30\1\0\27\30\24\0\3\30\5\0\6\30"+
    "\1\0\3\30\1\226\23\30\24\0\3\30\5\0\6\30"+
    "\1\0\15\30\1\227\11\30\24\0\3\30\5\0\6\30"+
    "\1\0\15\30\1\230\11\30\24\0\3\30\5\0\6\30"+
    "\1\0\7\30\1\231\17\30\24\0\3\30\5\0\6\30"+
    "\1\0\10\30\1\232\16\30\24\0\3\30\5\0\6\30"+
    "\1\0\13\30\1\233\13\30\24\0\3\30\5\0\6\30"+
    "\1\0\15\30\1\234\11\30\24\0\3\30\5\0\6\30"+
    "\1\0\23\30\1\235\3\30\24\0\3\30\5\0\6\30"+
    "\1\0\22\30\1\236\4\30\24\0\1\30\1\237\1\30"+
    "\5\0\6\30\1\0\27\30\24\0\3\30\5\0\6\30"+
    "\1\0\22\30\1\240\4\30\24\0\3\30\5\0\6\30"+
    "\1\0\24\30\1\241\2\30\24\0\3\30\5\0\6\30"+
    "\1\0\16\30\1\242\10\30\24\0\3\30\5\0\6\30"+
    "\1\0\5\30\1\243\21\30\24\0\3\30\5\0\6\30"+
    "\1\0\1\30\1\244\25\30\24\0\3\30\5\0\6\30"+
    "\1\0\22\30\1\245\4\30\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6612];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\3\11\1\1\1\11"+
    "\1\1\1\11\2\1\2\11\22\1\1\11\1\1\2\11"+
    "\1\0\1\11\1\0\1\11\2\0\4\11\1\0\1\1"+
    "\1\0\3\11\30\1\2\11\1\0\31\1\1\11\67\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token (TipoToken tipo, String lexema){
        return new Token(tipo, lexema, yyline + 1, yycolumn + 1);
    }    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return token(TipoToken.EOF, "EOF");
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(TipoToken.ERROR, yytext());
            }
          // fall through
          case 61: break;
          case 2:
            { 
            }
          // fall through
          case 62: break;
          case 3:
            { return token(TipoToken.NOT, yytext());
            }
          // fall through
          case 63: break;
          case 4:
            { return token(TipoToken.MODULO, yytext());
            }
          // fall through
          case 64: break;
          case 5:
            { return token(TipoToken.PARENTESIS_IZQ, yytext());
            }
          // fall through
          case 65: break;
          case 6:
            { return token(TipoToken.PARENTESIS_DER, yytext());
            }
          // fall through
          case 66: break;
          case 7:
            { return token(TipoToken.MULTIPLICACION, yytext());
            }
          // fall through
          case 67: break;
          case 8:
            { return token(TipoToken.MAS, yytext());
            }
          // fall through
          case 68: break;
          case 9:
            { return token(TipoToken.COMA, yytext());
            }
          // fall through
          case 69: break;
          case 10:
            { return token(TipoToken.MENOS, yytext());
            }
          // fall through
          case 70: break;
          case 11:
            { return token(TipoToken.PUNTO, yytext());
            }
          // fall through
          case 71: break;
          case 12:
            { return token(TipoToken.DIVISION, yytext());
            }
          // fall through
          case 72: break;
          case 13:
            { return token(TipoToken.ENTERO, yytext());
            }
          // fall through
          case 73: break;
          case 14:
            { return token(TipoToken.DOS_PUNTOS, yytext());
            }
          // fall through
          case 74: break;
          case 15:
            { return token(TipoToken.PUNTO_COMA, yytext());
            }
          // fall through
          case 75: break;
          case 16:
            { return token(TipoToken.MENOR, yytext());
            }
          // fall through
          case 76: break;
          case 17:
            { return token(TipoToken.IGUAL, yytext());
            }
          // fall through
          case 77: break;
          case 18:
            { return token(TipoToken.MAYOR, yytext());
            }
          // fall through
          case 78: break;
          case 19:
            { return token(TipoToken.IDENTIFICADOR, yytext());
            }
          // fall through
          case 79: break;
          case 20:
            { return token(TipoToken.LLAVE_IZQ, yytext());
            }
          // fall through
          case 80: break;
          case 21:
            { return token(TipoToken.LLAVE_DER, yytext());
            }
          // fall through
          case 81: break;
          case 22:
            { return token(TipoToken.DIFERENTE, yytext());
            }
          // fall through
          case 82: break;
          case 23:
            { return token(TipoToken.CADENA, yytext());
            }
          // fall through
          case 83: break;
          case 24:
            { return token(TipoToken.AND, yytext());
            }
          // fall through
          case 84: break;
          case 25:
            { return token(TipoToken.INCREMENTO, yytext());
            }
          // fall through
          case 85: break;
          case 26:
            { return token(TipoToken.MAS_IGUAL, yytext());
            }
          // fall through
          case 86: break;
          case 27:
            { return token(TipoToken.DECREMENTO, yytext());
            }
          // fall through
          case 87: break;
          case 28:
            { return token(TipoToken.MENOS_IGUAL, yytext());
            }
          // fall through
          case 88: break;
          case 29:
            { return token(TipoToken.MENOR_IGUAL, yytext());
            }
          // fall through
          case 89: break;
          case 30:
            { return token(TipoToken.IGUAL_IGUAL, yytext());
            }
          // fall through
          case 90: break;
          case 31:
            { return token(TipoToken.MAYOR_IGUAL, yytext());
            }
          // fall through
          case 91: break;
          case 32:
            { return token(TipoToken.IF, yytext());
            }
          // fall through
          case 92: break;
          case 33:
            { return token(TipoToken.OR, yytext());
            }
          // fall through
          case 93: break;
          case 34:
            { return token(TipoToken.LITERAL_RUNE, yytext());
            }
          // fall through
          case 94: break;
          case 35:
            { return token(TipoToken.DECIMAL, yytext());
            }
          // fall through
          case 95: break;
          case 36:
            { return token(TipoToken.FMT, yytext());
            }
          // fall through
          case 96: break;
          case 37:
            { return token(TipoToken.FOR, yytext());
            }
          // fall through
          case 97: break;
          case 38:
            { return token(TipoToken.INT, yytext());
            }
          // fall through
          case 98: break;
          case 39:
            { return token(TipoToken.NIL, yytext());
            }
          // fall through
          case 99: break;
          case 40:
            { return token(TipoToken.VAR, yytext());
            }
          // fall through
          case 100: break;
          case 41:
            { return token(TipoToken.ATOI, yytext());
            }
          // fall through
          case 101: break;
          case 42:
            { return token(TipoToken.BOOL, yytext());
            }
          // fall through
          case 102: break;
          case 43:
            { return token(TipoToken.CASE, yytext());
            }
          // fall through
          case 103: break;
          case 44:
            { return token(TipoToken.ELSE, yytext());
            }
          // fall through
          case 104: break;
          case 45:
            { return token(TipoToken.FUNC, yytext());
            }
          // fall through
          case 105: break;
          case 46:
            { return token(TipoToken.RUNE, yytext());
            }
          // fall through
          case 106: break;
          case 47:
            { return token(TipoToken.TRUE, yytext());
            }
          // fall through
          case 107: break;
          case 48:
            { return token(TipoToken.BREAK, yytext());
            }
          // fall through
          case 108: break;
          case 49:
            { return token(TipoToken.FALSE, yytext());
            }
          // fall through
          case 109: break;
          case 50:
            { return token(TipoToken.TYPEOF, yytext());
            }
          // fall through
          case 110: break;
          case 51:
            { return token(TipoToken.RETURN, yytext());
            }
          // fall through
          case 111: break;
          case 52:
            { return token(TipoToken.STRING, yytext());
            }
          // fall through
          case 112: break;
          case 53:
            { return token(TipoToken.SWITCH, yytext());
            }
          // fall through
          case 113: break;
          case 54:
            { return token(TipoToken.PRINTLN, yytext());
            }
          // fall through
          case 114: break;
          case 55:
            { return token(TipoToken.DEFAULT, yytext());
            }
          // fall through
          case 115: break;
          case 56:
            { return token(TipoToken.FLOAT64, yytext());
            }
          // fall through
          case 116: break;
          case 57:
            { return token(TipoToken.REFLECT, yytext());
            }
          // fall through
          case 117: break;
          case 58:
            { return token(TipoToken.STRCONV, yytext());
            }
          // fall through
          case 118: break;
          case 59:
            { return token(TipoToken.CONTINUE, yytext());
            }
          // fall through
          case 119: break;
          case 60:
            { return token(TipoToken.PARSEFLOAT, yytext());
            }
          // fall through
          case 120: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
