
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.olc1.golite.parser;

import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\075\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\003\000\002\004\003\000\002" +
    "\004\004\000\002\013\007\000\002\013\011\000\002\014" +
    "\007\000\002\015\004\000\002\016\004\000\002\005\007" +
    "\000\002\005\010\000\002\005\006\000\002\006\006\000" +
    "\002\006\006\000\002\006\006\000\002\007\011\000\002" +
    "\010\003\000\002\010\003\000\002\010\003\000\002\010" +
    "\003\000\002\010\003\000\002\010\003\000\002\010\003" +
    "\000\002\010\003\000\002\010\003\000\002\011\003\000" +
    "\002\011\005\000\002\011\005\000\002\011\005\000\002" +
    "\011\005\000\002\011\005\000\002\011\005\000\002\011" +
    "\005\000\002\011\005\000\002\011\005\000\002\011\005" +
    "\000\002\011\005\000\002\011\005\000\002\011\005\000" +
    "\002\011\005\000\002\011\004\000\002\011\004\000\002" +
    "\012\004\000\002\012\005\000\002\017\010\000\002\017" +
    "\010\000\002\017\010\000\002\020\003\000\002\020\003" +
    "\000\002\020\003\000\002\020\003\000\002\020\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\177\000\024\003\016\004\025\005\021\037\011\041" +
    "\024\042\005\055\022\064\015\065\004\001\002\000\004" +
    "\020\201\001\002\000\004\051\173\001\002\000\030\002" +
    "\ufffe\003\ufffe\004\ufffe\005\ufffe\037\ufffe\041\ufffe\042\ufffe" +
    "\055\ufffe\056\ufffe\064\ufffe\065\ufffe\001\002\000\030\002" +
    "\ufffd\003\ufffd\004\ufffd\005\ufffd\037\ufffd\041\ufffd\042\ufffd" +
    "\055\ufffd\056\ufffd\064\ufffd\065\ufffd\001\002\000\030\002" +
    "\ufff6\003\ufff6\004\ufff6\005\ufff6\037\ufff6\041\ufff6\042\ufff6" +
    "\055\ufff6\056\ufff6\064\ufff6\065\ufff6\001\002\000\004\053" +
    "\165\001\002\000\030\002\ufff8\003\ufff8\004\ufff8\005\ufff8" +
    "\037\ufff8\041\ufff8\042\ufff8\055\ufff8\056\ufff8\064\ufff8\065" +
    "\ufff8\001\002\000\030\002\ufffc\003\ufffc\004\ufffc\005\ufffc" +
    "\037\ufffc\041\ufffc\042\ufffc\055\ufffc\056\ufffc\064\ufffc\065" +
    "\ufffc\001\002\000\030\002\ufffa\003\ufffa\004\ufffa\005\ufffa" +
    "\037\ufffa\041\ufffa\042\ufffa\055\ufffa\056\ufffa\064\ufffa\065" +
    "\ufffa\001\002\000\004\020\164\001\002\000\004\020\163" +
    "\001\002\000\030\002\ufffb\003\ufffb\004\ufffb\005\ufffb\037" +
    "\ufffb\041\ufffb\042\ufffb\055\ufffb\056\ufffb\064\ufffb\065\ufffb" +
    "\001\002\000\030\002\ufff9\003\ufff9\004\ufff9\005\ufff9\037" +
    "\ufff9\041\ufff9\042\ufff9\055\ufff9\056\ufff9\064\ufff9\065\ufff9" +
    "\001\002\000\010\017\154\034\153\035\152\001\002\000" +
    "\026\003\016\004\025\005\021\037\011\041\024\042\005" +
    "\055\022\056\147\064\015\065\004\001\002\000\030\002" +
    "\ufff7\003\ufff7\004\ufff7\005\ufff7\037\ufff7\041\ufff7\042\ufff7" +
    "\055\ufff7\056\ufff7\064\ufff7\065\ufff7\001\002\000\004\053" +
    "\143\001\002\000\004\005\032\001\002\000\026\002\000" +
    "\003\016\004\025\005\021\037\011\041\024\042\005\055" +
    "\022\064\015\065\004\001\002\000\004\002\030\001\002" +
    "\000\004\002\001\001\002\000\030\002\uffff\003\uffff\004" +
    "\uffff\005\uffff\037\uffff\041\uffff\042\uffff\055\uffff\056\uffff" +
    "\064\uffff\065\uffff\001\002\000\016\011\040\012\041\013" +
    "\033\014\036\015\035\017\034\001\002\000\006\017\uffc7" +
    "\020\uffc7\001\002\000\034\005\063\006\054\007\046\010" +
    "\044\016\047\022\050\036\051\044\055\047\057\053\052" +
    "\061\060\062\053\063\056\001\002\000\006\017\uffc5\020" +
    "\uffc5\001\002\000\006\017\uffc6\020\uffc6\001\002\000\006" +
    "\017\042\020\043\001\002\000\006\017\uffc9\020\uffc9\001" +
    "\002\000\006\017\uffc8\020\uffc8\001\002\000\034\005\063" +
    "\006\054\007\046\010\044\016\047\022\050\036\051\044" +
    "\055\047\057\053\052\061\060\062\053\063\056\001\002" +
    "\000\030\002\uffed\003\uffed\004\uffed\005\uffed\037\uffed\041" +
    "\uffed\042\uffed\055\uffed\056\uffed\064\uffed\065\uffed\001\002" +
    "\000\040\020\uffe6\021\uffe6\022\uffe6\023\uffe6\024\uffe6\025" +
    "\uffe6\026\uffe6\027\uffe6\030\uffe6\031\uffe6\032\uffe6\033\uffe6" +
    "\054\uffe6\057\uffe6\060\uffe6\001\002\000\040\020\uffdf\021" +
    "\uffdf\022\uffdf\023\uffdf\024\uffdf\025\uffdf\026\uffdf\027\uffdf" +
    "\030\uffdf\031\uffdf\032\uffdf\033\uffdf\054\uffdf\057\uffdf\060" +
    "\uffdf\001\002\000\040\020\uffe7\021\uffe7\022\uffe7\023\uffe7" +
    "\024\uffe7\025\uffe7\026\uffe7\027\uffe7\030\uffe7\031\uffe7\032" +
    "\uffe7\033\uffe7\054\uffe7\057\uffe7\060\uffe7\001\002\000\040" +
    "\020\uffe1\021\uffe1\022\uffe1\023\uffe1\024\uffe1\025\uffe1\026" +
    "\uffe1\027\uffe1\030\uffe1\031\uffe1\032\uffe1\033\uffe1\054\uffe1" +
    "\057\uffe1\060\uffe1\001\002\000\034\005\063\006\054\007" +
    "\046\010\044\016\047\022\050\036\051\044\055\047\057" +
    "\053\052\061\060\062\053\063\056\001\002\000\040\020" +
    "\uffe2\021\uffe2\022\uffe2\023\uffe2\024\uffe2\025\uffe2\026\uffe2" +
    "\027\uffe2\030\uffe2\031\uffe2\032\uffe2\033\uffe2\054\uffe2\057" +
    "\uffe2\060\uffe2\001\002\000\034\005\063\006\054\007\046" +
    "\010\044\016\047\022\050\036\051\044\055\047\057\053" +
    "\052\061\060\062\053\063\056\001\002\000\040\020\uffe4" +
    "\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4\026\uffe4\027" +
    "\uffe4\030\uffe4\031\uffe4\032\uffe4\033\uffe4\054\uffe4\057\uffe4" +
    "\060\uffe4\001\002\000\040\020\uffe8\021\uffe8\022\uffe8\023" +
    "\uffe8\024\uffe8\025\uffe8\026\uffe8\027\uffe8\030\uffe8\031\uffe8" +
    "\032\uffe8\033\uffe8\054\uffe8\057\uffe8\060\uffe8\001\002\000" +
    "\004\051\125\001\002\000\040\020\uffe3\021\uffe3\022\uffe3" +
    "\023\uffe3\024\uffe3\025\uffe3\026\uffe3\027\uffe3\030\uffe3\031" +
    "\uffe3\032\uffe3\033\uffe3\054\uffe3\057\uffe3\060\uffe3\001\002" +
    "\000\004\051\120\001\002\000\034\005\063\006\054\007" +
    "\046\010\044\016\047\022\050\036\051\044\055\047\057" +
    "\053\052\061\060\062\053\063\056\001\002\000\036\020" +
    "\071\021\073\022\065\023\072\024\076\025\075\026\074" +
    "\027\066\030\070\031\100\032\067\033\077\057\064\060" +
    "\101\001\002\000\040\020\uffe0\021\uffe0\022\uffe0\023\uffe0" +
    "\024\uffe0\025\uffe0\026\uffe0\027\uffe0\030\uffe0\031\uffe0\032" +
    "\uffe0\033\uffe0\054\uffe0\057\uffe0\060\uffe0\001\002\000\040" +
    "\020\uffe5\021\uffe5\022\uffe5\023\uffe5\024\uffe5\025\uffe5\026" +
    "\uffe5\027\uffe5\030\uffe5\031\uffe5\032\uffe5\033\uffe5\054\uffe5" +
    "\057\uffe5\060\uffe5\001\002\000\034\005\063\006\054\007" +
    "\046\010\044\016\047\022\050\036\051\044\055\047\057" +
    "\053\052\061\060\062\053\063\056\001\002\000\034\005" +
    "\063\006\054\007\046\010\044\016\047\022\050\036\051" +
    "\044\055\047\057\053\052\061\060\062\053\063\056\001" +
    "\002\000\034\005\063\006\054\007\046\010\044\016\047" +
    "\022\050\036\051\044\055\047\057\053\052\061\060\062" +
    "\053\063\056\001\002\000\034\005\063\006\054\007\046" +
    "\010\044\016\047\022\050\036\051\044\055\047\057\053" +
    "\052\061\060\062\053\063\056\001\002\000\034\005\063" +
    "\006\054\007\046\010\044\016\047\022\050\036\051\044" +
    "\055\047\057\053\052\061\060\062\053\063\056\001\002" +
    "\000\030\002\uffee\003\uffee\004\uffee\005\uffee\037\uffee\041" +
    "\uffee\042\uffee\055\uffee\056\uffee\064\uffee\065\uffee\001\002" +
    "\000\034\005\063\006\054\007\046\010\044\016\047\022" +
    "\050\036\051\044\055\047\057\053\052\061\060\062\053" +
    "\063\056\001\002\000\034\005\063\006\054\007\046\010" +
    "\044\016\047\022\050\036\051\044\055\047\057\053\052" +
    "\061\060\062\053\063\056\001\002\000\034\005\063\006" +
    "\054\007\046\010\044\016\047\022\050\036\051\044\055" +
    "\047\057\053\052\061\060\062\053\063\056\001\002\000" +
    "\034\005\063\006\054\007\046\010\044\016\047\022\050" +
    "\036\051\044\055\047\057\053\052\061\060\062\053\063" +
    "\056\001\002\000\034\005\063\006\054\007\046\010\044" +
    "\016\047\022\050\036\051\044\055\047\057\053\052\061" +
    "\060\062\053\063\056\001\002\000\034\005\063\006\054" +
    "\007\046\010\044\016\047\022\050\036\051\044\055\047" +
    "\057\053\052\061\060\062\053\063\056\001\002\000\034" +
    "\005\063\006\054\007\046\010\044\016\047\022\050\036" +
    "\051\044\055\047\057\053\052\061\060\062\053\063\056" +
    "\001\002\000\034\005\063\006\054\007\046\010\044\016" +
    "\047\022\050\036\051\044\055\047\057\053\052\061\060" +
    "\062\053\063\056\001\002\000\040\020\uffd1\021\073\022" +
    "\065\023\072\024\076\025\075\026\074\027\066\030\070" +
    "\031\100\032\067\033\077\054\uffd1\057\064\060\uffd1\001" +
    "\002\000\040\020\uffd5\021\073\022\065\023\072\024\076" +
    "\025\075\026\uffd5\027\uffd5\030\uffd5\031\uffd5\032\uffd5\033" +
    "\uffd5\054\uffd5\057\uffd5\060\uffd5\001\002\000\040\020\uffd3" +
    "\021\073\022\065\023\072\024\076\025\075\026\074\027" +
    "\066\030\070\031\100\032\uffd3\033\uffd3\054\uffd3\057\uffd3" +
    "\060\uffd3\001\002\000\040\020\uffda\021\uffda\022\uffda\023" +
    "\uffda\024\uffda\025\uffda\026\uffda\027\uffda\030\uffda\031\uffda" +
    "\032\uffda\033\uffda\054\uffda\057\uffda\060\uffda\001\002\000" +
    "\040\020\uffd9\021\uffd9\022\uffd9\023\uffd9\024\uffd9\025\uffd9" +
    "\026\uffd9\027\uffd9\030\uffd9\031\uffd9\032\uffd9\033\uffd9\054" +
    "\uffd9\057\uffd9\060\uffd9\001\002\000\040\020\uffd8\021\073" +
    "\022\065\023\072\024\076\025\075\026\uffd8\027\uffd8\030" +
    "\uffd8\031\uffd8\032\uffd8\033\uffd8\054\uffd8\057\uffd8\060\uffd8" +
    "\001\002\000\040\020\uffdd\021\uffdd\022\uffdd\023\072\024" +
    "\076\025\075\026\uffdd\027\uffdd\030\uffdd\031\uffdd\032\uffdd" +
    "\033\uffdd\054\uffdd\057\uffdd\060\uffdd\001\002\000\040\020" +
    "\uffdb\021\uffdb\022\uffdb\023\uffdb\024\uffdb\025\uffdb\026\uffdb" +
    "\027\uffdb\030\uffdb\031\uffdb\032\uffdb\033\uffdb\054\uffdb\057" +
    "\uffdb\060\uffdb\001\002\000\040\020\uffd6\021\073\022\065" +
    "\023\072\024\076\025\075\026\uffd6\027\uffd6\030\uffd6\031" +
    "\uffd6\032\uffd6\033\uffd6\054\uffd6\057\uffd6\060\uffd6\001\002" +
    "\000\040\020\uffd4\021\073\022\065\023\072\024\076\025" +
    "\075\026\074\027\066\030\070\031\100\032\uffd4\033\uffd4" +
    "\054\uffd4\057\uffd4\060\uffd4\001\002\000\040\020\uffd7\021" +
    "\073\022\065\023\072\024\076\025\075\026\uffd7\027\uffd7" +
    "\030\uffd7\031\uffd7\032\uffd7\033\uffd7\054\uffd7\057\uffd7\060" +
    "\uffd7\001\002\000\040\020\uffdc\021\uffdc\022\uffdc\023\072" +
    "\024\076\025\075\026\uffdc\027\uffdc\030\uffdc\031\uffdc\032" +
    "\uffdc\033\uffdc\054\uffdc\057\uffdc\060\uffdc\001\002\000\040" +
    "\020\uffd2\021\073\022\065\023\072\024\076\025\075\026" +
    "\074\027\066\030\070\031\100\032\067\033\077\054\uffd2" +
    "\057\uffd2\060\uffd2\001\002\000\040\020\uffd0\021\uffd0\022" +
    "\uffd0\023\uffd0\024\uffd0\025\uffd0\026\uffd0\027\uffd0\030\uffd0" +
    "\031\uffd0\032\uffd0\033\uffd0\054\uffd0\057\uffd0\060\uffd0\001" +
    "\002\000\004\050\121\001\002\000\004\053\122\001\002" +
    "\000\034\005\063\006\054\007\046\010\044\016\047\022" +
    "\050\036\051\044\055\047\057\053\052\061\060\062\053" +
    "\063\056\001\002\000\036\021\073\022\065\023\072\024" +
    "\076\025\075\026\074\027\066\030\070\031\100\032\067" +
    "\033\077\054\124\057\064\060\101\001\002\000\040\020" +
    "\uffca\021\uffca\022\uffca\023\uffca\024\uffca\025\uffca\026\uffca" +
    "\027\uffca\030\uffca\031\uffca\032\uffca\033\uffca\054\uffca\057" +
    "\uffca\060\uffca\001\002\000\006\045\127\046\126\001\002" +
    "\000\004\053\133\001\002\000\004\053\130\001\002\000" +
    "\034\005\063\006\054\007\046\010\044\016\047\022\050" +
    "\036\051\044\055\047\057\053\052\061\060\062\053\063" +
    "\056\001\002\000\036\021\073\022\065\023\072\024\076" +
    "\025\075\026\074\027\066\030\070\031\100\032\067\033" +
    "\077\054\132\057\064\060\101\001\002\000\040\020\uffcc" +
    "\021\uffcc\022\uffcc\023\uffcc\024\uffcc\025\uffcc\026\uffcc\027" +
    "\uffcc\030\uffcc\031\uffcc\032\uffcc\033\uffcc\054\uffcc\057\uffcc" +
    "\060\uffcc\001\002\000\034\005\063\006\054\007\046\010" +
    "\044\016\047\022\050\036\051\044\055\047\057\053\052" +
    "\061\060\062\053\063\056\001\002\000\036\021\073\022" +
    "\065\023\072\024\076\025\075\026\074\027\066\030\070" +
    "\031\100\032\067\033\077\054\135\057\064\060\101\001" +
    "\002\000\040\020\uffcb\021\uffcb\022\uffcb\023\uffcb\024\uffcb" +
    "\025\uffcb\026\uffcb\027\uffcb\030\uffcb\031\uffcb\032\uffcb\033" +
    "\uffcb\054\uffcb\057\uffcb\060\uffcb\001\002\000\036\021\073" +
    "\022\065\023\072\024\076\025\075\026\074\027\066\030" +
    "\070\031\100\032\067\033\077\054\137\057\064\060\101" +
    "\001\002\000\040\020\uffde\021\uffde\022\uffde\023\uffde\024" +
    "\uffde\025\uffde\026\uffde\027\uffde\030\uffde\031\uffde\032\uffde" +
    "\033\uffde\054\uffde\057\uffde\060\uffde\001\002\000\040\020" +
    "\uffcf\021\uffcf\022\uffcf\023\uffcf\024\uffcf\025\uffcf\026\uffcf" +
    "\027\uffcf\030\uffcf\031\uffcf\032\uffcf\033\uffcf\054\uffcf\057" +
    "\uffcf\060\uffcf\001\002\000\036\020\142\021\073\022\065" +
    "\023\072\024\076\025\075\026\074\027\066\030\070\031" +
    "\100\032\067\033\077\057\064\060\101\001\002\000\030" +
    "\002\uffef\003\uffef\004\uffef\005\uffef\037\uffef\041\uffef\042" +
    "\uffef\055\uffef\056\uffef\064\uffef\065\uffef\001\002\000\034" +
    "\005\063\006\054\007\046\010\044\016\047\022\050\036" +
    "\051\044\055\047\057\053\052\061\060\062\053\063\056" +
    "\001\002\000\036\021\073\022\065\023\072\024\076\025" +
    "\075\026\074\027\066\030\070\031\100\032\067\033\077" +
    "\054\145\057\064\060\101\001\002\000\004\055\022\001" +
    "\002\000\030\002\ufff2\003\ufff2\004\ufff2\005\ufff2\037\ufff2" +
    "\041\ufff2\042\ufff2\055\ufff2\056\ufff2\064\ufff2\065\ufff2\001" +
    "\002\000\032\002\uffce\003\uffce\004\uffce\005\uffce\037\uffce" +
    "\040\uffce\041\uffce\042\uffce\055\uffce\056\uffce\064\uffce\065" +
    "\uffce\001\002\000\026\003\016\004\025\005\021\037\011" +
    "\041\024\042\005\055\022\056\151\064\015\065\004\001" +
    "\002\000\032\002\uffcd\003\uffcd\004\uffcd\005\uffcd\037\uffcd" +
    "\040\uffcd\041\uffcd\042\uffcd\055\uffcd\056\uffcd\064\uffcd\065" +
    "\uffcd\001\002\000\034\005\063\006\054\007\046\010\044" +
    "\016\047\022\050\036\051\044\055\047\057\053\052\061" +
    "\060\062\053\063\056\001\002\000\034\005\063\006\054" +
    "\007\046\010\044\016\047\022\050\036\051\044\055\047" +
    "\057\053\052\061\060\062\053\063\056\001\002\000\034" +
    "\005\063\006\054\007\046\010\044\016\047\022\050\036" +
    "\051\044\055\047\057\053\052\061\060\062\053\063\056" +
    "\001\002\000\036\020\156\021\073\022\065\023\072\024" +
    "\076\025\075\026\074\027\066\030\070\031\100\032\067" +
    "\033\077\057\064\060\101\001\002\000\030\002\uffec\003" +
    "\uffec\004\uffec\005\uffec\037\uffec\041\uffec\042\uffec\055\uffec" +
    "\056\uffec\064\uffec\065\uffec\001\002\000\036\020\160\021" +
    "\073\022\065\023\072\024\076\025\075\026\074\027\066" +
    "\030\070\031\100\032\067\033\077\057\064\060\101\001" +
    "\002\000\030\002\uffeb\003\uffeb\004\uffeb\005\uffeb\037\uffeb" +
    "\041\uffeb\042\uffeb\055\uffeb\056\uffeb\064\uffeb\065\uffeb\001" +
    "\002\000\036\020\162\021\073\022\065\023\072\024\076" +
    "\025\075\026\074\027\066\030\070\031\100\032\067\033" +
    "\077\057\064\060\101\001\002\000\030\002\uffea\003\uffea" +
    "\004\uffea\005\uffea\037\uffea\041\uffea\042\uffea\055\uffea\056" +
    "\uffea\064\uffea\065\uffea\001\002\000\030\002\ufff5\003\ufff5" +
    "\004\ufff5\005\ufff5\037\ufff5\041\ufff5\042\ufff5\055\ufff5\056" +
    "\ufff5\064\ufff5\065\ufff5\001\002\000\030\002\ufff1\003\ufff1" +
    "\004\ufff1\005\ufff1\037\ufff1\041\ufff1\042\ufff1\055\ufff1\056" +
    "\ufff1\064\ufff1\065\ufff1\001\002\000\034\005\063\006\054" +
    "\007\046\010\044\016\047\022\050\036\051\044\055\047" +
    "\057\053\052\061\060\062\053\063\056\001\002\000\036" +
    "\021\073\022\065\023\072\024\076\025\075\026\074\027" +
    "\066\030\070\031\100\032\067\033\077\054\167\057\064" +
    "\060\101\001\002\000\004\055\022\001\002\000\032\002" +
    "\ufff4\003\ufff4\004\ufff4\005\ufff4\037\ufff4\040\171\041\ufff4" +
    "\042\ufff4\055\ufff4\056\ufff4\064\ufff4\065\ufff4\001\002\000" +
    "\004\055\022\001\002\000\030\002\ufff3\003\ufff3\004\ufff3" +
    "\005\ufff3\037\ufff3\041\ufff3\042\ufff3\055\ufff3\056\ufff3\064" +
    "\ufff3\065\ufff3\001\002\000\004\043\174\001\002\000\004" +
    "\053\175\001\002\000\034\005\063\006\054\007\046\010" +
    "\044\016\047\022\050\036\051\044\055\047\057\053\052" +
    "\061\060\062\053\063\056\001\002\000\036\021\073\022" +
    "\065\023\072\024\076\025\075\026\074\027\066\030\070" +
    "\031\100\032\067\033\077\054\177\057\064\060\101\001" +
    "\002\000\004\020\200\001\002\000\030\002\uffe9\003\uffe9" +
    "\004\uffe9\005\uffe9\037\uffe9\041\uffe9\042\uffe9\055\uffe9\056" +
    "\uffe9\064\uffe9\065\uffe9\001\002\000\030\002\ufff0\003\ufff0" +
    "\004\ufff0\005\ufff0\037\ufff0\041\ufff0\042\ufff0\055\ufff0\056" +
    "\ufff0\064\ufff0\065\ufff0\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\177\000\030\002\026\003\025\004\005\005\006\006" +
    "\012\007\016\012\007\013\013\014\017\015\011\016\022" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\026\003\147\004\005\005" +
    "\006\006\012\007\016\012\007\013\013\014\017\015\011" +
    "\016\022\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\024\004\030\005\006\006\012\007\016" +
    "\012\007\013\013\014\017\015\011\016\022\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\020\036\001\001\000\002\001\001\000\010\010\044\011" +
    "\140\017\061\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\010\044\011\060\017\061\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\010\044\011\137\017\061\001\001" +
    "\000\002\001\001\000\010\010\044\011\135\017\061\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\010\044\011" +
    "\116\017\061\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\010\044\011\115\017\061\001" +
    "\001\000\010\010\044\011\114\017\061\001\001\000\010" +
    "\010\044\011\113\017\061\001\001\000\010\010\044\011" +
    "\112\017\061\001\001\000\010\010\044\011\111\017\061" +
    "\001\001\000\002\001\001\000\010\010\044\011\110\017" +
    "\061\001\001\000\010\010\044\011\107\017\061\001\001" +
    "\000\010\010\044\011\106\017\061\001\001\000\010\010" +
    "\044\011\105\017\061\001\001\000\010\010\044\011\104" +
    "\017\061\001\001\000\010\010\044\011\103\017\061\001" +
    "\001\000\010\010\044\011\102\017\061\001\001\000\010" +
    "\010\044\011\101\017\061\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\010\044\011\122" +
    "\017\061\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\010\044\011\130\017\061\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\010\044\011\133\017\061\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\010\044\011\143\017\061\001\001\000" +
    "\002\001\001\000\004\012\145\001\001\000\002\001\001" +
    "\000\002\001\001\000\024\004\030\005\006\006\012\007" +
    "\016\012\007\013\013\014\017\015\011\016\022\001\001" +
    "\000\002\001\001\000\010\010\044\011\160\017\061\001" +
    "\001\000\010\010\044\011\156\017\061\001\001\000\010" +
    "\010\044\011\154\017\061\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\010\044\011\165\017\061\001\001\000\002" +
    "\001\001\000\004\012\167\001\001\000\002\001\001\000" +
    "\004\012\171\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\010\044\011\175\017\061\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private java.util.List<com.olc1.golite.errors.ErrorCompilador> errores =
            new java.util.ArrayList<>();

    public java.util.List<com.olc1.golite.errors.ErrorCompilador> getErrores(){
        return errores;
    }

    @Override
    public void syntax_error(java_cup.runtime.Symbol s){

        errores.add(
            new com.olc1.golite.errors.ErrorCompilador(
                "Sintactico",
                "Token inesperado: " + s.value,
                s.left,
                s.right
            )
        );
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= LISTA_SENTENCIAS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LISTA_SENTENCIAS ::= LISTA_SENTENCIAS SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LISTA_SENTENCIAS ::= SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // SENTENCIA ::= DECLARACION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // SENTENCIA ::= ASIGNACION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SENTENCIA ::= PRINT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SENTENCIA ::= IF_SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTENCIA ::= FOR_SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTENCIA ::= BREAK_SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTENCIA ::= CONTINUE_SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SENTENCIA ::= BLOQUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTENCIA ::= error PUNTO_COMA 
            {
              Object RESULT =null;
		
            System.out.println("Sentencia invalida recuperada");
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // IF_SENTENCIA ::= IF PARENTESIS_IZQ EXPRESION PARENTESIS_DER BLOQUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("IF_SENTENCIA",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // IF_SENTENCIA ::= IF PARENTESIS_IZQ EXPRESION PARENTESIS_DER BLOQUE ELSE BLOQUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("IF_SENTENCIA",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // FOR_SENTENCIA ::= FOR PARENTESIS_IZQ EXPRESION PARENTESIS_DER BLOQUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FOR_SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // BREAK_SENTENCIA ::= BREAK PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("BREAK_SENTENCIA",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // CONTINUE_SENTENCIA ::= CONTINUE PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CONTINUE_SENTENCIA",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // DECLARACION ::= VAR IDENTIFICADOR IGUAL EXPRESION PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // DECLARACION ::= VAR IDENTIFICADOR TIPO IGUAL EXPRESION PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // DECLARACION ::= VAR IDENTIFICADOR TIPO PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // ASIGNACION ::= IDENTIFICADOR IGUAL EXPRESION PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASIGNACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // ASIGNACION ::= IDENTIFICADOR MAS_IGUAL EXPRESION PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASIGNACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // ASIGNACION ::= IDENTIFICADOR MENOS_IGUAL EXPRESION PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASIGNACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // PRINT ::= FMT PUNTO PRINTLN PARENTESIS_IZQ EXPRESION PARENTESIS_DER PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRINT",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // VALOR ::= ENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // VALOR ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // VALOR ::= CADENA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // VALOR ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // VALOR ::= TRUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // VALOR ::= FALSE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // VALOR ::= NIL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // VALOR ::= LITERAL_RUNE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // VALOR ::= FUNCION_EMBEBIDA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // EXPRESION ::= VALOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // EXPRESION ::= PARENTESIS_IZQ EXPRESION PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // EXPRESION ::= EXPRESION MAS EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // EXPRESION ::= EXPRESION MENOS EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // EXPRESION ::= EXPRESION MULTIPLICACION EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // EXPRESION ::= EXPRESION DIVISION EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // EXPRESION ::= EXPRESION MODULO EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // EXPRESION ::= EXPRESION MAYOR EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // EXPRESION ::= EXPRESION MENOR EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // EXPRESION ::= EXPRESION MAYOR_IGUAL EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // EXPRESION ::= EXPRESION MENOR_IGUAL EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // EXPRESION ::= EXPRESION IGUAL_IGUAL EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // EXPRESION ::= EXPRESION DIFERENTE EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // EXPRESION ::= EXPRESION AND EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // EXPRESION ::= EXPRESION OR EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // EXPRESION ::= NOT EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // EXPRESION ::= MENOS EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // BLOQUE ::= LLAVE_IZQ LLAVE_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("BLOQUE",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // BLOQUE ::= LLAVE_IZQ LISTA_SENTENCIAS LLAVE_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("BLOQUE",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // FUNCION_EMBEBIDA ::= STRCONV PUNTO ATOI PARENTESIS_IZQ EXPRESION PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUNCION_EMBEBIDA",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // FUNCION_EMBEBIDA ::= STRCONV PUNTO PARSEFLOAT PARENTESIS_IZQ EXPRESION PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUNCION_EMBEBIDA",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // FUNCION_EMBEBIDA ::= REFLECT PUNTO TYPEOF PARENTESIS_IZQ EXPRESION PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUNCION_EMBEBIDA",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // TIPO ::= INT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // TIPO ::= FLOAT64 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // TIPO ::= STRING 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // TIPO ::= BOOL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // TIPO ::= RUNE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
