
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.olc1.golite.parser;

import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\103\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\003\000\002\004\003\000\002" +
    "\004\004\000\002\013\007\000\002\013\011\000\002\013" +
    "\011\000\002\014\007\000\002\015\004\000\002\016\004" +
    "\000\002\005\007\000\002\005\010\000\002\005\006\000" +
    "\002\006\006\000\002\006\007\000\002\006\006\000\002" +
    "\006\006\000\002\006\005\000\002\006\005\000\002\007" +
    "\011\000\002\010\003\000\002\010\003\000\002\010\003" +
    "\000\002\010\003\000\002\010\003\000\002\010\003\000" +
    "\002\010\003\000\002\010\003\000\002\010\003\000\002" +
    "\011\003\000\002\011\005\000\002\011\005\000\002\011" +
    "\005\000\002\011\005\000\002\011\005\000\002\011\005" +
    "\000\002\011\005\000\002\011\005\000\002\011\005\000" +
    "\002\011\005\000\002\011\005\000\002\011\005\000\002" +
    "\011\005\000\002\011\005\000\002\011\004\000\002\011" +
    "\004\000\002\012\004\000\002\012\005\000\002\017\010" +
    "\000\002\017\010\000\002\017\010\000\002\020\003\000" +
    "\002\020\003\000\002\020\003\000\002\020\003\000\002" +
    "\020\003\000\002\021\003\000\002\021\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\213\000\024\003\016\004\025\005\021\040\011\042" +
    "\024\043\005\056\022\065\015\066\004\001\002\000\004" +
    "\020\215\001\002\000\004\052\204\001\002\000\030\002" +
    "\ufffe\003\ufffe\004\ufffe\005\ufffe\040\ufffe\042\ufffe\043\ufffe" +
    "\056\ufffe\057\ufffe\065\ufffe\066\ufffe\001\002\000\030\002" +
    "\ufffd\003\ufffd\004\ufffd\005\ufffd\040\ufffd\042\ufffd\043\ufffd" +
    "\056\ufffd\057\ufffd\065\ufffd\066\ufffd\001\002\000\030\002" +
    "\ufff6\003\ufff6\004\ufff6\005\ufff6\040\ufff6\042\ufff6\043\ufff6" +
    "\056\ufff6\057\ufff6\065\ufff6\066\ufff6\001\002\000\004\054" +
    "\175\001\002\000\030\002\ufff8\003\ufff8\004\ufff8\005\ufff8" +
    "\040\ufff8\042\ufff8\043\ufff8\056\ufff8\057\ufff8\065\ufff8\066" +
    "\ufff8\001\002\000\030\002\ufffc\003\ufffc\004\ufffc\005\ufffc" +
    "\040\ufffc\042\ufffc\043\ufffc\056\ufffc\057\ufffc\065\ufffc\066" +
    "\ufffc\001\002\000\030\002\ufffa\003\ufffa\004\ufffa\005\ufffa" +
    "\040\ufffa\042\ufffa\043\ufffa\056\ufffa\057\ufffa\065\ufffa\066" +
    "\ufffa\001\002\000\004\020\174\001\002\000\004\020\173" +
    "\001\002\000\030\002\ufffb\003\ufffb\004\ufffb\005\ufffb\040" +
    "\ufffb\042\ufffb\043\ufffb\056\ufffb\057\ufffb\065\ufffb\066\ufffb" +
    "\001\002\000\030\002\ufff9\003\ufff9\004\ufff9\005\ufff9\040" +
    "\ufff9\042\ufff9\043\ufff9\056\ufff9\057\ufff9\065\ufff9\066\ufff9" +
    "\001\002\000\016\017\155\021\156\035\154\036\152\067" +
    "\157\070\153\001\002\000\026\003\016\004\025\005\021" +
    "\040\011\042\024\043\005\056\022\057\147\065\015\066" +
    "\004\001\002\000\030\002\ufff7\003\ufff7\004\ufff7\005\ufff7" +
    "\040\ufff7\042\ufff7\043\ufff7\056\ufff7\057\ufff7\065\ufff7\066" +
    "\ufff7\001\002\000\004\054\143\001\002\000\004\005\032" +
    "\001\002\000\026\002\000\003\016\004\025\005\021\040" +
    "\011\042\024\043\005\056\022\065\015\066\004\001\002" +
    "\000\004\002\030\001\002\000\004\002\001\001\002\000" +
    "\030\002\uffff\003\uffff\004\uffff\005\uffff\040\uffff\042\uffff" +
    "\043\uffff\056\uffff\057\uffff\065\uffff\066\uffff\001\002\000" +
    "\016\011\041\012\040\013\033\014\036\015\035\017\034" +
    "\001\002\000\006\017\uffc3\020\uffc3\001\002\000\034\005" +
    "\063\006\053\007\046\010\044\016\047\023\050\037\051" +
    "\045\055\050\057\054\052\062\060\063\054\064\056\001" +
    "\002\000\006\017\uffc1\020\uffc1\001\002\000\006\017\uffc2" +
    "\020\uffc2\001\002\000\006\017\042\020\043\001\002\000" +
    "\006\017\uffc4\020\uffc4\001\002\000\006\017\uffc5\020\uffc5" +
    "\001\002\000\034\005\063\006\053\007\046\010\044\016" +
    "\047\023\050\037\051\045\055\050\057\054\052\062\060" +
    "\063\054\064\056\001\002\000\030\002\uffec\003\uffec\004" +
    "\uffec\005\uffec\040\uffec\042\uffec\043\uffec\056\uffec\057\uffec" +
    "\065\uffec\066\uffec\001\002\000\042\020\uffe2\022\uffe2\023" +
    "\uffe2\024\uffe2\025\uffe2\026\uffe2\027\uffe2\030\uffe2\031\uffe2" +
    "\032\uffe2\033\uffe2\034\uffe2\053\uffe2\055\uffe2\060\uffe2\061" +
    "\uffe2\001\002\000\042\020\uffdb\022\uffdb\023\uffdb\024\uffdb" +
    "\025\uffdb\026\uffdb\027\uffdb\030\uffdb\031\uffdb\032\uffdb\033" +
    "\uffdb\034\uffdb\053\uffdb\055\uffdb\060\uffdb\061\uffdb\001\002" +
    "\000\042\020\uffe3\022\uffe3\023\uffe3\024\uffe3\025\uffe3\026" +
    "\uffe3\027\uffe3\030\uffe3\031\uffe3\032\uffe3\033\uffe3\034\uffe3" +
    "\053\uffe3\055\uffe3\060\uffe3\061\uffe3\001\002\000\042\020" +
    "\uffdd\022\uffdd\023\uffdd\024\uffdd\025\uffdd\026\uffdd\027\uffdd" +
    "\030\uffdd\031\uffdd\032\uffdd\033\uffdd\034\uffdd\053\uffdd\055" +
    "\uffdd\060\uffdd\061\uffdd\001\002\000\034\005\063\006\053" +
    "\007\046\010\044\016\047\023\050\037\051\045\055\050" +
    "\057\054\052\062\060\063\054\064\056\001\002\000\042" +
    "\020\uffde\022\uffde\023\uffde\024\uffde\025\uffde\026\uffde\027" +
    "\uffde\030\uffde\031\uffde\032\uffde\033\uffde\034\uffde\053\uffde" +
    "\055\uffde\060\uffde\061\uffde\001\002\000\034\005\063\006" +
    "\053\007\046\010\044\016\047\023\050\037\051\045\055" +
    "\050\057\054\052\062\060\063\054\064\056\001\002\000" +
    "\042\020\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4\026\uffe4" +
    "\027\uffe4\030\uffe4\031\uffe4\032\uffe4\033\uffe4\034\uffe4\053" +
    "\uffe4\055\uffe4\060\uffe4\061\uffe4\001\002\000\042\020\uffe0" +
    "\022\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0\027\uffe0\030" +
    "\uffe0\031\uffe0\032\uffe0\033\uffe0\034\uffe0\053\uffe0\055\uffe0" +
    "\060\uffe0\061\uffe0\001\002\000\004\052\125\001\002\000" +
    "\042\020\uffdf\022\uffdf\023\uffdf\024\uffdf\025\uffdf\026\uffdf" +
    "\027\uffdf\030\uffdf\031\uffdf\032\uffdf\033\uffdf\034\uffdf\053" +
    "\uffdf\055\uffdf\060\uffdf\061\uffdf\001\002\000\004\052\120" +
    "\001\002\000\034\005\063\006\053\007\046\010\044\016" +
    "\047\023\050\037\051\045\055\050\057\054\052\062\060" +
    "\063\054\064\056\001\002\000\042\020\uffdc\022\uffdc\023" +
    "\uffdc\024\uffdc\025\uffdc\026\uffdc\027\uffdc\030\uffdc\031\uffdc" +
    "\032\uffdc\033\uffdc\034\uffdc\053\uffdc\055\uffdc\060\uffdc\061" +
    "\uffdc\001\002\000\036\020\070\022\073\023\065\024\072" +
    "\025\076\026\075\027\074\030\066\031\071\032\101\033" +
    "\067\034\077\060\064\061\100\001\002\000\042\020\uffe1" +
    "\022\uffe1\023\uffe1\024\uffe1\025\uffe1\026\uffe1\027\uffe1\030" +
    "\uffe1\031\uffe1\032\uffe1\033\uffe1\034\uffe1\053\uffe1\055\uffe1" +
    "\060\uffe1\061\uffe1\001\002\000\034\005\063\006\053\007" +
    "\046\010\044\016\047\023\050\037\051\045\055\050\057" +
    "\054\052\062\060\063\054\064\056\001\002\000\034\005" +
    "\063\006\053\007\046\010\044\016\047\023\050\037\051" +
    "\045\055\050\057\054\052\062\060\063\054\064\056\001" +
    "\002\000\034\005\063\006\053\007\046\010\044\016\047" +
    "\023\050\037\051\045\055\050\057\054\052\062\060\063" +
    "\054\064\056\001\002\000\034\005\063\006\053\007\046" +
    "\010\044\016\047\023\050\037\051\045\055\050\057\054" +
    "\052\062\060\063\054\064\056\001\002\000\030\002\uffed" +
    "\003\uffed\004\uffed\005\uffed\040\uffed\042\uffed\043\uffed\056" +
    "\uffed\057\uffed\065\uffed\066\uffed\001\002\000\034\005\063" +
    "\006\053\007\046\010\044\016\047\023\050\037\051\045" +
    "\055\050\057\054\052\062\060\063\054\064\056\001\002" +
    "\000\034\005\063\006\053\007\046\010\044\016\047\023" +
    "\050\037\051\045\055\050\057\054\052\062\060\063\054" +
    "\064\056\001\002\000\034\005\063\006\053\007\046\010" +
    "\044\016\047\023\050\037\051\045\055\050\057\054\052" +
    "\062\060\063\054\064\056\001\002\000\034\005\063\006" +
    "\053\007\046\010\044\016\047\023\050\037\051\045\055" +
    "\050\057\054\052\062\060\063\054\064\056\001\002\000" +
    "\034\005\063\006\053\007\046\010\044\016\047\023\050" +
    "\037\051\045\055\050\057\054\052\062\060\063\054\064" +
    "\056\001\002\000\034\005\063\006\053\007\046\010\044" +
    "\016\047\023\050\037\051\045\055\050\057\054\052\062" +
    "\060\063\054\064\056\001\002\000\034\005\063\006\053" +
    "\007\046\010\044\016\047\023\050\037\051\045\055\050" +
    "\057\054\052\062\060\063\054\064\056\001\002\000\034" +
    "\005\063\006\053\007\046\010\044\016\047\023\050\037" +
    "\051\045\055\050\057\054\052\062\060\063\054\064\056" +
    "\001\002\000\034\005\063\006\053\007\046\010\044\016" +
    "\047\023\050\037\051\045\055\050\057\054\052\062\060" +
    "\063\054\064\056\001\002\000\042\020\uffd1\022\073\023" +
    "\065\024\072\025\076\026\075\027\uffd1\030\uffd1\031\uffd1" +
    "\032\uffd1\033\uffd1\034\uffd1\053\uffd1\055\uffd1\060\uffd1\061" +
    "\uffd1\001\002\000\042\020\uffcd\022\073\023\065\024\072" +
    "\025\076\026\075\027\074\030\066\031\071\032\101\033" +
    "\067\034\077\053\uffcd\055\uffcd\060\064\061\uffcd\001\002" +
    "\000\042\020\uffcf\022\073\023\065\024\072\025\076\026" +
    "\075\027\074\030\066\031\071\032\101\033\uffcf\034\uffcf" +
    "\053\uffcf\055\uffcf\060\uffcf\061\uffcf\001\002\000\042\020" +
    "\uffd6\022\uffd6\023\uffd6\024\uffd6\025\uffd6\026\uffd6\027\uffd6" +
    "\030\uffd6\031\uffd6\032\uffd6\033\uffd6\034\uffd6\053\uffd6\055" +
    "\uffd6\060\uffd6\061\uffd6\001\002\000\042\020\uffd5\022\uffd5" +
    "\023\uffd5\024\uffd5\025\uffd5\026\uffd5\027\uffd5\030\uffd5\031" +
    "\uffd5\032\uffd5\033\uffd5\034\uffd5\053\uffd5\055\uffd5\060\uffd5" +
    "\061\uffd5\001\002\000\042\020\uffd4\022\073\023\065\024" +
    "\072\025\076\026\075\027\uffd4\030\uffd4\031\uffd4\032\uffd4" +
    "\033\uffd4\034\uffd4\053\uffd4\055\uffd4\060\uffd4\061\uffd4\001" +
    "\002\000\042\020\uffd9\022\uffd9\023\uffd9\024\072\025\076" +
    "\026\075\027\uffd9\030\uffd9\031\uffd9\032\uffd9\033\uffd9\034" +
    "\uffd9\053\uffd9\055\uffd9\060\uffd9\061\uffd9\001\002\000\042" +
    "\020\uffd7\022\uffd7\023\uffd7\024\uffd7\025\uffd7\026\uffd7\027" +
    "\uffd7\030\uffd7\031\uffd7\032\uffd7\033\uffd7\034\uffd7\053\uffd7" +
    "\055\uffd7\060\uffd7\061\uffd7\001\002\000\042\020\uffd2\022" +
    "\073\023\065\024\072\025\076\026\075\027\uffd2\030\uffd2" +
    "\031\uffd2\032\uffd2\033\uffd2\034\uffd2\053\uffd2\055\uffd2\060" +
    "\uffd2\061\uffd2\001\002\000\042\020\uffd0\022\073\023\065" +
    "\024\072\025\076\026\075\027\074\030\066\031\071\032" +
    "\101\033\uffd0\034\uffd0\053\uffd0\055\uffd0\060\uffd0\061\uffd0" +
    "\001\002\000\042\020\uffd3\022\073\023\065\024\072\025" +
    "\076\026\075\027\uffd3\030\uffd3\031\uffd3\032\uffd3\033\uffd3" +
    "\034\uffd3\053\uffd3\055\uffd3\060\uffd3\061\uffd3\001\002\000" +
    "\042\020\uffd8\022\uffd8\023\uffd8\024\072\025\076\026\075" +
    "\027\uffd8\030\uffd8\031\uffd8\032\uffd8\033\uffd8\034\uffd8\053" +
    "\uffd8\055\uffd8\060\uffd8\061\uffd8\001\002\000\042\020\uffce" +
    "\022\073\023\065\024\072\025\076\026\075\027\074\030" +
    "\066\031\071\032\101\033\067\034\077\053\uffce\055\uffce" +
    "\060\uffce\061\uffce\001\002\000\042\020\uffcc\022\uffcc\023" +
    "\uffcc\024\uffcc\025\uffcc\026\uffcc\027\uffcc\030\uffcc\031\uffcc" +
    "\032\uffcc\033\uffcc\034\uffcc\053\uffcc\055\uffcc\060\uffcc\061" +
    "\uffcc\001\002\000\004\051\121\001\002\000\004\054\122" +
    "\001\002\000\034\005\063\006\053\007\046\010\044\016" +
    "\047\023\050\037\051\045\055\050\057\054\052\062\060" +
    "\063\054\064\056\001\002\000\036\022\073\023\065\024" +
    "\072\025\076\026\075\027\074\030\066\031\071\032\101" +
    "\033\067\034\077\055\124\060\064\061\100\001\002\000" +
    "\042\020\uffc6\022\uffc6\023\uffc6\024\uffc6\025\uffc6\026\uffc6" +
    "\027\uffc6\030\uffc6\031\uffc6\032\uffc6\033\uffc6\034\uffc6\053" +
    "\uffc6\055\uffc6\060\uffc6\061\uffc6\001\002\000\006\046\127" +
    "\047\126\001\002\000\004\054\133\001\002\000\004\054" +
    "\130\001\002\000\034\005\063\006\053\007\046\010\044" +
    "\016\047\023\050\037\051\045\055\050\057\054\052\062" +
    "\060\063\054\064\056\001\002\000\036\022\073\023\065" +
    "\024\072\025\076\026\075\027\074\030\066\031\071\032" +
    "\101\033\067\034\077\055\132\060\064\061\100\001\002" +
    "\000\042\020\uffc8\022\uffc8\023\uffc8\024\uffc8\025\uffc8\026" +
    "\uffc8\027\uffc8\030\uffc8\031\uffc8\032\uffc8\033\uffc8\034\uffc8" +
    "\053\uffc8\055\uffc8\060\uffc8\061\uffc8\001\002\000\034\005" +
    "\063\006\053\007\046\010\044\016\047\023\050\037\051" +
    "\045\055\050\057\054\052\062\060\063\054\064\056\001" +
    "\002\000\036\022\073\023\065\024\072\025\076\026\075" +
    "\027\074\030\066\031\071\032\101\033\067\034\077\055" +
    "\135\060\064\061\100\001\002\000\042\020\uffc7\022\uffc7" +
    "\023\uffc7\024\uffc7\025\uffc7\026\uffc7\027\uffc7\030\uffc7\031" +
    "\uffc7\032\uffc7\033\uffc7\034\uffc7\053\uffc7\055\uffc7\060\uffc7" +
    "\061\uffc7\001\002\000\036\022\073\023\065\024\072\025" +
    "\076\026\075\027\074\030\066\031\071\032\101\033\067" +
    "\034\077\055\137\060\064\061\100\001\002\000\042\020" +
    "\uffda\022\uffda\023\uffda\024\uffda\025\uffda\026\uffda\027\uffda" +
    "\030\uffda\031\uffda\032\uffda\033\uffda\034\uffda\053\uffda\055" +
    "\uffda\060\uffda\061\uffda\001\002\000\042\020\uffcb\022\uffcb" +
    "\023\uffcb\024\uffcb\025\uffcb\026\uffcb\027\uffcb\030\uffcb\031" +
    "\uffcb\032\uffcb\033\uffcb\034\uffcb\053\uffcb\055\uffcb\060\uffcb" +
    "\061\uffcb\001\002\000\036\020\142\022\073\023\065\024" +
    "\072\025\076\026\075\027\074\030\066\031\071\032\101" +
    "\033\067\034\077\060\064\061\100\001\002\000\030\002" +
    "\uffee\003\uffee\004\uffee\005\uffee\040\uffee\042\uffee\043\uffee" +
    "\056\uffee\057\uffee\065\uffee\066\uffee\001\002\000\034\005" +
    "\063\006\053\007\046\010\044\016\047\023\050\037\051" +
    "\045\055\050\057\054\052\062\060\063\054\064\056\001" +
    "\002\000\036\022\073\023\065\024\072\025\076\026\075" +
    "\027\074\030\066\031\071\032\101\033\067\034\077\055" +
    "\145\060\064\061\100\001\002\000\004\056\022\001\002" +
    "\000\030\002\ufff1\003\ufff1\004\ufff1\005\ufff1\040\ufff1\042" +
    "\ufff1\043\ufff1\056\ufff1\057\ufff1\065\ufff1\066\ufff1\001\002" +
    "\000\032\002\uffca\003\uffca\004\uffca\005\uffca\040\uffca\041" +
    "\uffca\042\uffca\043\uffca\056\uffca\057\uffca\065\uffca\066\uffca" +
    "\001\002\000\026\003\016\004\025\005\021\040\011\042" +
    "\024\043\005\056\022\057\151\065\015\066\004\001\002" +
    "\000\032\002\uffc9\003\uffc9\004\uffc9\005\uffc9\040\uffc9\041" +
    "\uffc9\042\uffc9\043\uffc9\056\uffc9\057\uffc9\065\uffc9\066\uffc9" +
    "\001\002\000\034\005\063\006\053\007\046\010\044\016" +
    "\047\023\050\037\051\045\055\050\057\054\052\062\060" +
    "\063\054\064\056\001\002\000\004\020\170\001\002\000" +
    "\034\005\063\006\053\007\046\010\044\016\047\023\050" +
    "\037\051\045\055\050\057\054\052\062\060\063\054\064" +
    "\056\001\002\000\034\005\063\006\053\007\046\010\044" +
    "\016\047\023\050\037\051\045\055\050\057\054\052\062" +
    "\060\063\054\064\056\001\002\000\004\017\161\001\002" +
    "\000\004\020\160\001\002\000\030\002\uffe7\003\uffe7\004" +
    "\uffe7\005\uffe7\040\uffe7\042\uffe7\043\uffe7\056\uffe7\057\uffe7" +
    "\065\uffe7\066\uffe7\001\002\000\034\005\063\006\053\007" +
    "\046\010\044\016\047\023\050\037\051\045\055\050\057" +
    "\054\052\062\060\063\054\064\056\001\002\000\036\020" +
    "\163\022\073\023\065\024\072\025\076\026\075\027\074" +
    "\030\066\031\071\032\101\033\067\034\077\060\064\061" +
    "\100\001\002\000\030\002\uffea\003\uffea\004\uffea\005\uffea" +
    "\040\uffea\042\uffea\043\uffea\056\uffea\057\uffea\065\uffea\066" +
    "\uffea\001\002\000\036\020\165\022\073\023\065\024\072" +
    "\025\076\026\075\027\074\030\066\031\071\032\101\033" +
    "\067\034\077\060\064\061\100\001\002\000\030\002\uffeb" +
    "\003\uffeb\004\uffeb\005\uffeb\040\uffeb\042\uffeb\043\uffeb\056" +
    "\uffeb\057\uffeb\065\uffeb\066\uffeb\001\002\000\036\020\167" +
    "\022\073\023\065\024\072\025\076\026\075\027\074\030" +
    "\066\031\071\032\101\033\067\034\077\060\064\061\100" +
    "\001\002\000\030\002\uffe9\003\uffe9\004\uffe9\005\uffe9\040" +
    "\uffe9\042\uffe9\043\uffe9\056\uffe9\057\uffe9\065\uffe9\066\uffe9" +
    "\001\002\000\030\002\uffe6\003\uffe6\004\uffe6\005\uffe6\040" +
    "\uffe6\042\uffe6\043\uffe6\056\uffe6\057\uffe6\065\uffe6\066\uffe6" +
    "\001\002\000\036\020\172\022\073\023\065\024\072\025" +
    "\076\026\075\027\074\030\066\031\071\032\101\033\067" +
    "\034\077\060\064\061\100\001\002\000\030\002\uffe8\003" +
    "\uffe8\004\uffe8\005\uffe8\040\uffe8\042\uffe8\043\uffe8\056\uffe8" +
    "\057\uffe8\065\uffe8\066\uffe8\001\002\000\030\002\ufff5\003" +
    "\ufff5\004\ufff5\005\ufff5\040\ufff5\042\ufff5\043\ufff5\056\ufff5" +
    "\057\ufff5\065\ufff5\066\ufff5\001\002\000\030\002\ufff0\003" +
    "\ufff0\004\ufff0\005\ufff0\040\ufff0\042\ufff0\043\ufff0\056\ufff0" +
    "\057\ufff0\065\ufff0\066\ufff0\001\002\000\034\005\063\006" +
    "\053\007\046\010\044\016\047\023\050\037\051\045\055" +
    "\050\057\054\052\062\060\063\054\064\056\001\002\000" +
    "\036\022\073\023\065\024\072\025\076\026\075\027\074" +
    "\030\066\031\071\032\101\033\067\034\077\055\177\060" +
    "\064\061\100\001\002\000\004\056\022\001\002\000\032" +
    "\002\ufff4\003\ufff4\004\ufff4\005\ufff4\040\ufff4\041\201\042" +
    "\ufff4\043\ufff4\056\ufff4\057\ufff4\065\ufff4\066\ufff4\001\002" +
    "\000\006\040\011\056\022\001\002\000\030\002\ufff2\003" +
    "\ufff2\004\ufff2\005\ufff2\040\ufff2\042\ufff2\043\ufff2\056\ufff2" +
    "\057\ufff2\065\ufff2\066\ufff2\001\002\000\030\002\ufff3\003" +
    "\ufff3\004\ufff3\005\ufff3\040\ufff3\042\ufff3\043\ufff3\056\ufff3" +
    "\057\ufff3\065\ufff3\066\ufff3\001\002\000\004\044\205\001" +
    "\002\000\004\054\206\001\002\000\034\005\063\006\053" +
    "\007\046\010\044\016\047\023\050\037\051\045\055\050" +
    "\057\054\052\062\060\063\054\064\056\001\002\000\006" +
    "\053\211\055\212\001\002\000\040\022\073\023\065\024" +
    "\072\025\076\026\075\027\074\030\066\031\071\032\101" +
    "\033\067\034\077\053\uffc0\055\uffc0\060\064\061\100\001" +
    "\002\000\034\005\063\006\053\007\046\010\044\016\047" +
    "\023\050\037\051\045\055\050\057\054\052\062\060\063" +
    "\054\064\056\001\002\000\004\020\213\001\002\000\030" +
    "\002\uffe5\003\uffe5\004\uffe5\005\uffe5\040\uffe5\042\uffe5\043" +
    "\uffe5\056\uffe5\057\uffe5\065\uffe5\066\uffe5\001\002\000\040" +
    "\022\073\023\065\024\072\025\076\026\075\027\074\030" +
    "\066\031\071\032\101\033\067\034\077\053\uffbf\055\uffbf" +
    "\060\064\061\100\001\002\000\030\002\uffef\003\uffef\004" +
    "\uffef\005\uffef\040\uffef\042\uffef\043\uffef\056\uffef\057\uffef" +
    "\065\uffef\066\uffef\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\213\000\030\002\026\003\025\004\005\005\006\006" +
    "\012\007\016\012\007\013\013\014\017\015\011\016\022" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\026\003\147\004\005\005" +
    "\006\006\012\007\016\012\007\013\013\014\017\015\011" +
    "\016\022\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\024\004\030\005\006\006\012\007\016" +
    "\012\007\013\013\014\017\015\011\016\022\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\020\036\001\001\000\002\001\001\000\010\010\044\011" +
    "\140\017\060\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\010\044\011\061\017\060\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\010\044\011\137\017\060\001\001" +
    "\000\002\001\001\000\010\010\044\011\135\017\060\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\010\044\011" +
    "\116\017\060\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\010\044\011\115\017\060\001" +
    "\001\000\010\010\044\011\114\017\060\001\001\000\010" +
    "\010\044\011\113\017\060\001\001\000\010\010\044\011" +
    "\112\017\060\001\001\000\002\001\001\000\010\010\044" +
    "\011\111\017\060\001\001\000\010\010\044\011\110\017" +
    "\060\001\001\000\010\010\044\011\107\017\060\001\001" +
    "\000\010\010\044\011\106\017\060\001\001\000\010\010" +
    "\044\011\105\017\060\001\001\000\010\010\044\011\104" +
    "\017\060\001\001\000\010\010\044\011\103\017\060\001" +
    "\001\000\010\010\044\011\102\017\060\001\001\000\010" +
    "\010\044\011\101\017\060\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\010\044\011\122" +
    "\017\060\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\010\044\011\130\017\060\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\010\044\011\133\017\060\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\010\044\011\143\017\060\001\001\000" +
    "\002\001\001\000\004\012\145\001\001\000\002\001\001" +
    "\000\002\001\001\000\024\004\030\005\006\006\012\007" +
    "\016\012\007\013\013\014\017\015\011\016\022\001\001" +
    "\000\002\001\001\000\010\010\044\011\170\017\060\001" +
    "\001\000\002\001\001\000\010\010\044\011\165\017\060" +
    "\001\001\000\010\010\044\011\163\017\060\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\010\044\011\161\017\060\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\010\044\011\175\017\060\001\001\000\002\001" +
    "\001\000\004\012\177\001\001\000\002\001\001\000\006" +
    "\012\201\013\202\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\010\044" +
    "\011\207\017\060\021\206\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\010\044\011\213\017\060\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private java.util.List<com.olc1.golite.errors.ErrorCompilador> errores =
            new java.util.ArrayList<>();

    public java.util.List<com.olc1.golite.errors.ErrorCompilador> getErrores(){
        return errores;
    }

    @Override
    public void syntax_error(java_cup.runtime.Symbol s){

        errores.add(
            new com.olc1.golite.errors.ErrorCompilador(
                "Sintactico",
                "Token inesperado: " + s.value,
                s.left,
                s.right
            )
        );

        System.out.println(
            "ERROR -> " + s.value +
            " linea=" + s.left +
            " columna=" + s.right
        );
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= LISTA_SENTENCIAS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LISTA_SENTENCIAS ::= LISTA_SENTENCIAS SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LISTA_SENTENCIAS ::= SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // SENTENCIA ::= DECLARACION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // SENTENCIA ::= ASIGNACION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SENTENCIA ::= PRINT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SENTENCIA ::= IF_SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTENCIA ::= FOR_SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTENCIA ::= BREAK_SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTENCIA ::= CONTINUE_SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SENTENCIA ::= BLOQUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTENCIA ::= error PUNTO_COMA 
            {
              Object RESULT =null;
		
            System.out.println("Sentencia invalida recuperada");
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // IF_SENTENCIA ::= IF PARENTESIS_IZQ EXPRESION PARENTESIS_DER BLOQUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("IF_SENTENCIA",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // IF_SENTENCIA ::= IF PARENTESIS_IZQ EXPRESION PARENTESIS_DER BLOQUE ELSE IF_SENTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("IF_SENTENCIA",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // IF_SENTENCIA ::= IF PARENTESIS_IZQ EXPRESION PARENTESIS_DER BLOQUE ELSE BLOQUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("IF_SENTENCIA",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // FOR_SENTENCIA ::= FOR PARENTESIS_IZQ EXPRESION PARENTESIS_DER BLOQUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FOR_SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // BREAK_SENTENCIA ::= BREAK PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("BREAK_SENTENCIA",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // CONTINUE_SENTENCIA ::= CONTINUE PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CONTINUE_SENTENCIA",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // DECLARACION ::= VAR IDENTIFICADOR IGUAL EXPRESION PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // DECLARACION ::= VAR IDENTIFICADOR TIPO IGUAL EXPRESION PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // DECLARACION ::= VAR IDENTIFICADOR TIPO PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // ASIGNACION ::= IDENTIFICADOR IGUAL EXPRESION PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASIGNACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // ASIGNACION ::= IDENTIFICADOR DOS_PUNTOS IGUAL EXPRESION PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASIGNACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // ASIGNACION ::= IDENTIFICADOR MAS_IGUAL EXPRESION PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASIGNACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // ASIGNACION ::= IDENTIFICADOR MENOS_IGUAL EXPRESION PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASIGNACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // ASIGNACION ::= IDENTIFICADOR INCREMENTO PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASIGNACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ASIGNACION ::= IDENTIFICADOR DECREMENTO PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASIGNACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // PRINT ::= FMT PUNTO PRINTLN PARENTESIS_IZQ LISTA_EXPRESIONES PARENTESIS_DER PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRINT",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // VALOR ::= ENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // VALOR ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // VALOR ::= CADENA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // VALOR ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // VALOR ::= TRUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // VALOR ::= FALSE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // VALOR ::= NIL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // VALOR ::= LITERAL_RUNE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // VALOR ::= FUNCION_EMBEBIDA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // EXPRESION ::= VALOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // EXPRESION ::= PARENTESIS_IZQ EXPRESION PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // EXPRESION ::= EXPRESION MAS EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // EXPRESION ::= EXPRESION MENOS EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // EXPRESION ::= EXPRESION MULTIPLICACION EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // EXPRESION ::= EXPRESION DIVISION EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // EXPRESION ::= EXPRESION MODULO EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // EXPRESION ::= EXPRESION MAYOR EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // EXPRESION ::= EXPRESION MENOR EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // EXPRESION ::= EXPRESION MAYOR_IGUAL EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // EXPRESION ::= EXPRESION MENOR_IGUAL EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // EXPRESION ::= EXPRESION IGUAL_IGUAL EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // EXPRESION ::= EXPRESION DIFERENTE EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // EXPRESION ::= EXPRESION AND EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // EXPRESION ::= EXPRESION OR EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // EXPRESION ::= NOT EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // EXPRESION ::= MENOS EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // BLOQUE ::= LLAVE_IZQ LLAVE_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("BLOQUE",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // BLOQUE ::= LLAVE_IZQ LISTA_SENTENCIAS LLAVE_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("BLOQUE",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // FUNCION_EMBEBIDA ::= STRCONV PUNTO ATOI PARENTESIS_IZQ EXPRESION PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUNCION_EMBEBIDA",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // FUNCION_EMBEBIDA ::= STRCONV PUNTO PARSEFLOAT PARENTESIS_IZQ EXPRESION PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUNCION_EMBEBIDA",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // FUNCION_EMBEBIDA ::= REFLECT PUNTO TYPEOF PARENTESIS_IZQ EXPRESION PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUNCION_EMBEBIDA",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // TIPO ::= INT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // TIPO ::= FLOAT64 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // TIPO ::= STRING 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // TIPO ::= BOOL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // TIPO ::= RUNE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // LISTA_EXPRESIONES ::= EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTA_EXPRESIONES",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // LISTA_EXPRESIONES ::= LISTA_EXPRESIONES COMA EXPRESION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTA_EXPRESIONES",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
